Repository googleapis/release-please, pull requests merged in 2019-05, with the labels that each got.

#9 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#10 feat: you must now opt in to bumping minor pre-major
  src/bin/release-please.ts
  src/conventional-commits.ts
  src/mint-release.ts
  test/conventional-commits.ts
Labels: cla: yes

#11 fix: allow executable
  src/bin/release-please.ts
  src/conventional-commits.ts
Labels: cla: yes

#13 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#7 build: getting CI running
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/lint.sh
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
  .kokoro/samples-test.sh
  .kokoro/test.sh
  package-lock.json
  package.json
  synth.metadata
  system-test/github.ts
  test/updaters/changelog.ts
Labels: cla: yes

#6 fix: support H2 and H3 CHANGELOG headings
  __snapshots__/changelog.js
  src/updaters/changelog.ts
  test/updaters/changelog.ts
  test/updaters/fixtures/CHANGELOG-fix.md
Labels: cla: yes

#15 fix: log message was printing undefined version
  .kokoro/test.bat
  src/updaters/samples-package-json.ts
Labels: cla: yes

#19 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#21 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#22 test: output from html report was overwriting lcov report
  .c8rc
  package.json
Labels: cla: yes

#24 fix: could not handle the very first release of a library before it had any tags.
  package.json
  src/bin/release-please.ts
  src/github.ts
  src/mint-release.ts
  system-test/github.ts
Labels: cla: yes

#27 feat: adding a GitHub action for releasing
  .github/action/mint-release/Dockerfile
  .github/action/mint-release/LICENSE.txt
  .github/action/mint-release/entrypoint.sh
Labels: cla: yes

#28 build: switching to running workflow when new comment is created
  .github/action/mint-release/entrypoint.sh
  .github/main.workflow
Labels: cla: yes

#58 build: switch to JavaScript check scripts for triggering action
  .github/action/mint-release/Dockerfile
  .github/action/mint-release/check.js
  .github/action/mint-release/entrypoint.sh
Labels: cla: yes

#59 build: apply ACL to the creation of releases
  .github/action/mint-release/Dockerfile
  .github/action/mint-release/check.js
  .github/main.workflow
Labels: cla: yes

#61 fix: there was a typo in failure output
  .github/action/mint-release/check.js
Labels: cla: yes

#69 feat: add GitHub action for generating candidate issue
  .github/action/candidate-issue/Dockerfile
  .github/action/candidate-issue/LICENSE.txt
  .github/action/candidate-issue/entrypoint.sh
  .github/main.workflow
Labels: cla: yes

#70 fix: candidate issue should only be updated every 15 minutes.
  .github/main.workflow
Labels: cla: yes

#77 feat: checkbox based releases
  src/bin/release-please.ts
  src/candidate-issue.ts
  src/github.ts
  src/mint-release.ts
  system-test/github.ts
Labels: cla: yes

#84 refactor: `MintRelease` is better described as `ReleasePR`
  src/bin/release-please.ts
  src/candidate-issue.ts
  src/github.ts
  src/release-pr.ts
Labels: cla: yes

#85 feat: introduce GitHub release functionality
  .github/action/release-please/Dockerfile
  .github/action/release-please/LICENSE.txt
  .github/action/release-please/entrypoint.sh
  .github/main.workflow
  __snapshots__/github-release.js
  package-lock.json
  src/bin/release-please.ts
  src/github-release.ts
  src/github.ts
  system-test/github.ts
  test/fixtures/CHANGELOG-new.md
  test/fixtures/CHANGELOG-old-new.md
  test/fixtures/CHANGELOG-old.md
  test/github-release.ts
Labels: cla: yes

#87 feat: add command for generating action config
  src/bin/release-please.ts
Labels: cla: yes

#88 feat: don't remove link to PR until new commits landed
  __snapshots__/candidate-issue.js
  src/candidate-issue.ts
  test/candidate-issue.ts
Labels: cla: yes

#89 fix: Node 10 is required for async/await
  package.json
  src/candidate-issue.ts
Labels: cla: yes

#91 build: switch to running 1.3.0 in GitHub action
  .github/action/release-please/Dockerfile
Labels: cla: yes

#92 fix: GitHub issues do not allow 'link comments'
  __snapshots__/candidate-issue.js
  src/candidate-issue.ts
  system-test/github.ts
Labels: cla: yes

#93 feat: introduce detect-checked command, a quick check for whether a release has been requested
  .github/main.workflow
  package-lock.json
  src/bin/release-please.ts
  src/candidate-issue.ts
  src/github.ts
  src/release-pr.ts
  system-test/github.ts
Labels: cla: yes

#103 build: update package version for automation
  .github/action/release-please/Dockerfile
Labels: cla: yes

#101 build: adding kokoro config for release-please
  .kokoro/release-candidate-issue.sh
  .kokoro/release-github.sh
  .kokoro/release-requested.sh
  .kokoro/release/common.cfg
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-github.cfg
  .kokoro/release/release-requested.cfg
Labels: cla: yes

#108 fix: output labels in log
  src/github.ts
Labels: cla: yes

#109 chore: release 1.4.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes

#110 test: testing codecov's claim that they merge coverage
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
Labels: cla: yes

#112 build: move codecov token to common
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/test.cfg
Labels: cla: yes

#117 refactor: reworked release-pr logic, to work better in isolation
  package-lock.json
  src/bin/release-please.ts
  src/candidate-issue.ts
  src/github-release.ts
  src/github.ts
  src/release-pr.ts
  system-test/github.ts
Labels: automerge, cla: yes

#118 build: updated kokoro config for release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-github.sh
  .kokoro/release-requested.sh
  .kokoro/release/common.cfg
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-github.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#120 chore: release 1.4.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes

#125 build: updated kokoro config for coverage and release-please
  synth.metadata
Labels: cla: yes

#126 chore: release 1.5.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes, type: process

#132 fix: if we generate a CHANGELOG with only a header, don't open a PR
  package-lock.json
  src/github.ts
  src/release-pr.ts
  system-test/github.ts
Labels: cla: yes

#133 fix: adding additional labels could potentially break CHANGELOG generation logic
  src/github.ts
Labels: cla: yes

#134 chore: release 1.5.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes, type: process

#136 docs: update docs to reflect current usage
  .readme-partials.yml
  .repo-metadata.json
  README.md
  src/bin/release-please.ts
Labels: cla: yes

#137 feat: BREAKING CHANGE moved to top of template
  package-lock.json
  package.json
Labels: cla: yes

#139 chore: release 1.6.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes, type: process

#142 fix: extend release notes regex to support patches
  __snapshots__/github-release.js
  src/github-release.ts
  test/fixtures/CHANGELOG-bug-140.md
  test/github-release.ts
Labels: cla: yes

#152 fix: force update branch rather than closing and reopening PRs
  package-lock.json
  src/github.ts
  src/release-pr.ts
  system-test/github.ts
Labels: cla: yes

#153 chore: release 1.6.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes, type: process

#156 chore: remove nodejs-repo-tools
  __snapshots__/samples-package-json.js
  package-lock.json
  test/updaters/fixtures/samples-package.json
Labels: cla: yes

#157 s/libary/library
  README.md
Labels: cla: yes

#160 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#167 docs: fix a minor spelling error
  .readme-partials.yml
Labels: cla: yes

#169 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes

#180 feat: refactor to accept --proxy-key and --api-url
  __snapshots__/release-pr.js
  package-lock.json
  package.json
  src/bin/release-please.ts
  src/github-release.ts
  src/github.ts
  src/release-pr.ts
  test/release-pr.ts
Labels: cla: yes
