Repository googleapis/release-please, pull requests merged in 2019-06, with the labels that each got.

#183 docs: clean up README
  .kokoro/presubmit/node10/system-test.cfg
  README.md
  synth.metadata
Labels: cla: yes

#184 test: get tests passing again
  __snapshots__/release-pr.js
  src/github.ts
  test/release-pr.ts
Labels: cla: yes

#185 feat: allow secrets to be loaded from path
  src/bin/release-please.ts
  src/conventional-commits.ts
  src/github-release.ts
  src/github.ts
  src/release-pr.ts
  src/updaters/changelog.ts
  src/updaters/package-json.ts
  src/updaters/samples-package-json.ts
  src/updaters/version.ts
  src/util/checkpoint.ts
  src/util/coerce-option.ts
  test/fixtures/key.txt
  test/util/coerce-option.ts
Labels: cla: yes

#186 feat!: update GitHub action to run on PR rather than commit
  .github/action/release-please/Dockerfile
  .github/action/release-please/entrypoint.sh
  src/bin/release-please.ts
  src/github.ts
Labels: cla: yes

#181 chore: release 2.0.0
  CHANGELOG.md
  package.json
Labels: :rotating_light:, autorelease: pending, cla: yes, type: process

#187 build: switch to using GitHub magic proxy
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
Labels: cla: yes

#188 fix: should use single = for bash comparison
  .github/action/release-please/entrypoint.sh
Labels: cla: yes

#190 fix: bash script still had a couple bugs
  .github/action/release-please/entrypoint.sh
Labels: cla: yes

#191 test: get integration tests working again
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/system-test.cfg
  .kokoro/system-test.sh
  synth.py
  system-test/github.ts
  test/release-pr.ts
Labels: cla: yes

#189 chore: release 2.0.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes, type: process

#192 feat: avoid updating release PR if no additional changes
  __snapshots__/release-pr.js
  package-lock.json
  src/github.ts
  src/release-pr.ts
Labels: cla: yes

#193 chore: release 2.1.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes, type: process

#196 chore: release 2.2.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes, type: process

#197 fix: src/manifest.json needs 'v' prefix and top level version
  __snapshots__/release-pr.js
  src/release-pr.ts
  src/updaters/php-manifest.ts
  test/release-pr.ts
Labels: cla: yes

#198 chore: release 2.2.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes, type: process

#199 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
  README.md
Labels: cla: yes

#201 build: use config file for linkinator
  linkinator.config.json
Labels: cla: yes
