Repository googleapis/release-please, pull requests merged in 2020-10, with the labels that each got.

#559 chore: update bucket for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#560 feat: add support for versioning by version.py for python packages
  __snapshots__/version-py.js
  src/releasers/python.ts
  src/updaters/python/version-py.ts
  test/updaters/fixtures/version.py
  test/updaters/version-py.ts
Labels: cla: yes

#578 test: a dependency now expects / encoded as %2F
  test/github-release.ts
  test/release-pr.ts
  test/releasers/java-yoshi.ts
  test/releasers/node.ts
Labels: cla: yes

#561 build(node_library): migrate to Trampoline V2
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  synth.metadata
Labels: automerge: exact, cla: yes, context: full

#429 feat: add support for releasing from non-master branches for legacy support
  __snapshots__/commit-split.js
  __snapshots__/github.js
  __snapshots__/graphql-to-commits.js
  __snapshots__/release-pr.js
  src/github-release.ts
  src/github.ts
  src/graphql-to-commits.ts
  test/fixtures/commits-with-labels.json
  test/fixtures/commits-yoshi-php-monorepo.json
  test/github-release.ts
  test/github.ts
  test/release-pr-factory.ts
  test/release-pr.ts
  test/releasers/fixtures/java-bom/commits-with-feature.json
  test/releasers/fixtures/java-bom/commits.json
  test/releasers/fixtures/java-yoshi/commits-yoshi-java.json
  test/releasers/fixtures/node/commits.json
  test/releasers/fixtures/simple/commits.json
  test/releasers/fixtures/yoshi-go/commits.json
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
  test/releasers/node.ts
  test/releasers/simple.ts
  test/releasers/yoshi-go.ts
Labels: cla: yes

#585 fix: sort commits from graphql output by descending commit date so we get fresh results
  src/github.ts
Labels: cla: yes

#591 build: only check --engine-strict for production deps
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#587 fix: issues found by testing with the GCP ruby repo
  __snapshots__/commit-split.js
  __snapshots__/github.js
  __snapshots__/graphql-to-commits.js
  __snapshots__/release-pr.js
  src/github.ts
  src/graphql-to-commits.ts
  test/fixtures/commits-with-labels.json
  test/fixtures/commits-yoshi-php-monorepo.json
  test/github-release.ts
  test/github.ts
  test/release-pr-factory.ts
  test/release-pr.ts
  test/releasers/fixtures/java-bom/commits-with-feature.json
  test/releasers/fixtures/java-bom/commits.json
  test/releasers/fixtures/java-yoshi/commits-yoshi-java.json
  test/releasers/fixtures/java-yoshi/empty-commits.json
  test/releasers/fixtures/node/commits.json
  test/releasers/fixtures/simple/commits.json
  test/releasers/fixtures/yoshi-go/commits.json
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
  test/releasers/node.ts
  test/releasers/simple.ts
  test/releasers/yoshi-go.ts
Labels: cla: yes

#594 fix: pagination logic broken in merge
  src/github.ts
Labels: cla: yes

#554 feat(go): generalize to also support google-api-go-client
  __snapshots__/commit-split.js
  __snapshots__/github-release.js
  __snapshots__/github.js
  __snapshots__/graphql-to-commits.js
  __snapshots__/java-bom.js
  __snapshots__/java-yoshi.js
  __snapshots__/node.js
  __snapshots__/simple.js
  __snapshots__/yoshi-go.js
  src/github.ts
  src/releasers/go-yoshi.ts
  test/fixtures/pojos/commits-fix.json
  test/helpers.ts
  test/releasers/fixtures/yoshi-go/cloud-go-commits.json
  test/releasers/fixtures/yoshi-go/discovery-commits.json
  test/releasers/simple.ts
  test/releasers/yoshi-go.ts
Labels: cla: yes

#603 docs: updated code of conduct (includes update to actions)
  .github/workflows/ci.yaml
  .kokoro/release/docs-devsite.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: cla: yes, context: full

#600 docs: Yarn how to comment
  README.md
Labels: cla: yes

#604 fix(go): ignore tags with prefix, if no prefix provided
  __snapshots__/commit-split.js
  __snapshots__/github-release.js
  __snapshots__/github.js
  __snapshots__/graphql-to-commits.js
  __snapshots__/java-bom.js
  __snapshots__/java-yoshi.js
  __snapshots__/node.js
  __snapshots__/yoshi-go.js
  src/github.ts
  test/github.ts
Labels: cla: yes

#606 fix(graphql): graphql query requested pagination at wrong level/did n…
  __snapshots__/java-yoshi.js
  __snapshots__/node.js
  src/github.ts
  test/releasers/java-yoshi.ts
  test/releasers/node.ts
Labels: cla: yes

#608 feat: Support the Ruby releaser from the static ReleasePRFactory
  src/release-pr-factory.ts
  src/release-pr.ts
Labels: cla: yes

#610 feat(java): support special case of promotion to 1.0.0
  __snapshots__/java-yoshi.js
  src/releasers/java-yoshi.ts
  src/releasers/java/stability.ts
  test/releasers/fixtures/java-yoshi/commits-promote-ga.json
  test/releasers/fixtures/java-yoshi/pre-ga-versions.txt
  test/releasers/java-yoshi.ts
  test/releasers/java/stability.ts
Labels: cla: yes
