Repository googleapis/release-please, pull requests merged in 2020-07, with the labels that each got.

#479 feat(snapshot): skip snapshot releases for releasers that lack this concept
  src/release-pr.ts
  src/releasers/java-auth-yoshi.ts
  src/releasers/java-bom.ts
  src/releasers/java-yoshi.ts
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
  test/releasers/node.ts
Labels: cla: yes

#478 refactor(snapshot): do not delay before running snapshot logic
  src/releasers/java-bom.ts
  src/releasers/java-yoshi.ts
Labels: cla: yes

#481 fix: skip Java releases if snapshot is specified, but does not match repo state
  src/releasers/java-bom.ts
  src/releasers/java-yoshi.ts
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
Labels: cla: yes

#483 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#484 fix: exception was thrown when 0 commits found
  src/releasers/java-auth-yoshi.ts
  src/releasers/java-bom.ts
  src/releasers/java-yoshi.ts
Labels: cla: yes

#486 build: typo in gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#489 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#492 build: missing parenthesis in publish script, delete Node 8 tests, add config for cloud-rad for nodejs
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#493 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#494 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#491 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes, context: none

#490 fix: missing authorization header for repos.get()
  src/github.ts
Labels: cla: yes

#495 fix(node): reorder files added, so that skip logic works
  __snapshots__/node.js
  src/releasers/node.ts
Labels: cla: yes

#497 chore: we are getting a false security warning
  __snapshots__/package-json.js
  test/updaters/fixtures/package.json
Labels: cla: yes

#498 fix: use conventional commits for our own commits
  __snapshots__/java-yoshi.js
  __snapshots__/node.js
  __snapshots__/simple.js
  src/github.ts
Labels: cla: yes

#499 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#501 feat: add support for monorepos/releasing from alternate folders
  README.md
  __snapshots__/node.js
  src/bin/release-please.ts
  src/github-release.ts
  src/github.ts
  src/release-pr.ts
  src/releasers/java-auth-yoshi.ts
  src/releasers/java-bom.ts
  src/releasers/java-yoshi.ts
  src/releasers/node.ts
  src/releasers/php-yoshi.ts
  src/releasers/python.ts
  src/releasers/ruby-yoshi.ts
  src/releasers/ruby.ts
  src/releasers/simple.ts
  src/releasers/terraform-module.ts
  test/releasers/node.ts
Labels: cla: yes

#504 fix(java-snapshot): handle no new commits since release
  __snapshots__/java-yoshi.js
  src/releasers/java-bom.ts
  src/releasers/java-yoshi.ts
  test/releasers/fixtures/java-yoshi/empty-commits.json
  test/releasers/java-yoshi.ts
Labels: cla: yes

#508 docs: fix link for python example
  README.md
Labels: cla: yes

#509 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: cla: yes, context: full
