Repository googleapis/release-please, pull requests merged in 2020-08, with the labels that each got.

#512 fix: looser parsing of versions.txt
  src/updaters/java/versions-manifest.ts
  test/releasers/java/versions-manifest.ts
Labels: cla: yes

#516 build: --credential-file-override is no longer required
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#514 feat(go): add support for releasing yoshi gapic go libraries
  __snapshots__/yoshi-go.js
  package.json
  src/conventional-commits.ts
  src/releasers/go-yoshi.ts
  test/releasers/fixtures/yoshi-go/commits.json
  test/releasers/yoshi-go.ts
Labels: cla: yes

#518 fix(java): detect need for snapshot unless a snapshot is explicitly requested
  __snapshots__/java-bom.js
  __snapshots__/java-yoshi.js
  __snapshots__/yoshi-go.js
  src/releasers/java-bom.ts
  src/releasers/java-yoshi.ts
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
  test/releasers/java/versions-manifest.ts
Labels: cla: yes

#520 fix(go): Update scope matching and regen regex
  __snapshots__/yoshi-go.js
  src/releasers/go-yoshi.ts
  test/releasers/fixtures/yoshi-go/commits.json
Labels: cla: yes

#521 build: update publish and docs scripts
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes, context: full

#523 fix(yoshi-go): store the sha of the first commit
  __snapshots__/yoshi-go.js
  src/releasers/go-yoshi.ts
Labels: cla: yes

#525 feat: add typescript exports from index
  src/index.ts
Labels: cla: yes

#527 feat: allow CHANGELOG path to be set
  src/bin/release-please.ts
  src/github-release.ts
Labels: cla: yes

#528 chore: start tracking obsolete files
  synth.metadata
Labels: automerge, cla: yes, context: full

#529 feat(release-as): release-as now supports pre-release
  src/release-pr.ts
Labels: cla: yes

#533 build: track flaky tests for "nightly", add new secrets for tagging
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
