Repository googleapis/release-please, pull requests merged in 2020-06, with the labels that each got.

#451 docs: fix typos in README
  README.md
Labels: automerge, cla: yes

#452 fix: merge commits now handled
  src/graphql-to-commits.ts
  test/fixtures/commits-with-labels.json
Labels: cla: yes

#457 feat(java-yoshi): handle build.gradle and dependencies.properties files
  src/releasers/java-yoshi.ts
  test/releasers/java-yoshi.ts
Labels: cla: yes

#460 fix: list commits of type `docs` for python
  src/releasers/python.ts
Labels: automerge, cla: yes

#456 build(secrets): begin migration to secret manager from keystore
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#466 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: cla: yes, context: full

#468 feat: detect default branch
  README.md
  __snapshots__/java-bom.js
  __snapshots__/java-yoshi.js
  __snapshots__/release-pr-factory.js
  __snapshots__/release-pr.js
  __snapshots__/simple.js
  src/bin/release-please.ts
  src/github.ts
  src/graphql-to-commits.ts
  src/release-pr.ts
  test/fixtures/repo-get-1.json
  test/fixtures/repo-get-2.json
  test/release-pr-factory.ts
  test/release-pr.ts
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
  test/releasers/simple.ts
Labels: cla: yes

#467 feat(node): update version number in package-lock.json
  __snapshots__/node.js
  src/releasers/node.ts
  test/releasers/fixtures/node/commits.json
  test/releasers/fixtures/node/package-lock.json
  test/releasers/fixtures/node/package.json
  test/releasers/node.ts
Labels: cla: yes

#448 docs: explain how to automate publication
  README.md
Labels: cla: yes

#472 fix: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#476 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
