Repository googleapis/release-please, pull requests merged in 2020-05, with the labels that each got.

#422 chore: unpin version of gts
  package.json
Labels: automerge, cla: yes

#424 fix(java): logging message should not crash when there's no latestTag
  src/releasers/java-yoshi.ts
Labels: cla: yes

#427 fix: don't include pre-release in latestTag calculation
  __snapshots__/java-bom.js
  src/github.ts
  test/github.ts
Labels: cla: yes

#433 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#436 feat: simple version.txt releaser
  __snapshots__/simple.js
  __snapshots__/version-txt.js
  src/release-pr.ts
  src/releasers/simple.ts
  src/updaters/version-txt.ts
  test/releasers/fixtures/simple/commits.json
  test/releasers/fixtures/simple/version.txt
  test/releasers/simple.ts
  test/updaters/version-txt.ts
Labels: cla: yes

#438 feat: return the release created by createRelease()
  src/github-release.ts
  src/github.ts
  test/github-release.ts
Labels: cla: yes

#439 refactor!: dynamically load releasers in ./releasers directory
  __snapshots__/changelog.js
  __snapshots__/commit-split.js
  __snapshots__/conventional-commits.js
  __snapshots__/github-release.js
  __snapshots__/github.js
  __snapshots__/graphql-to-commits.js
  __snapshots__/indent-commit.js
  __snapshots__/java-auth-readme.js
  __snapshots__/java-auth-versions.js
  __snapshots__/java-yoshi.js
  __snapshots__/package-json.js
  __snapshots__/pom-xml.js
  __snapshots__/readme.js
  __snapshots__/release-pr.js
  __snapshots__/root-composer.js
  __snapshots__/samples-package-json.js
  __snapshots__/setup-cfg.js
  __snapshots__/setup-py.js
  __snapshots__/version-manifest.js
  __snapshots__/version-rb.js
  src/bin/release-please.ts
  src/github-release.ts
  src/github.ts
  src/graphql-to-commits.ts
  src/release-pr-factory.ts
  src/release-pr.ts
  src/releasers/index.ts
  src/releasers/java-auth-yoshi.ts
  src/releasers/java-bom.ts
  src/releasers/java-yoshi.ts
  src/releasers/node.ts
  src/releasers/php-yoshi.ts
  src/releasers/python.ts
  src/releasers/ruby-yoshi.ts
  src/releasers/ruby.ts
  src/releasers/simple.ts
  src/releasers/terraform-module.ts
  src/updaters/php-client-version.ts
  src/updaters/version.ts
  test/github-release.ts
  test/github.ts
  test/release-pr.ts
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
  test/releasers/simple.ts
  test/updaters/changelog.ts
  test/updaters/java-auth-readme.ts
  test/updaters/java-auth-versions.ts
  test/updaters/package-json.ts
  test/updaters/readme.ts
  test/updaters/root-composer.ts
  test/updaters/samples-package-json.ts
Labels: cla: yes

#442 feat: introduce static factory helper
  __snapshots__/release-pr-factory.js
  src/release-pr-factory.ts
  src/releasers/index.ts
  test/release-pr-factory.ts
Labels: cla: yes

#443 feat: a flag to skip CI
  __snapshots__/java-yoshi.js
  __snapshots__/simple.js
  src/github.ts
  src/releasers/simple.ts
  src/updaters/changelog.ts
  src/updaters/java/google-utils.ts
  src/updaters/java/java_update.ts
  src/updaters/package-json.ts
  src/updaters/php-client-version.ts
  src/updaters/php-manifest.ts
  src/updaters/python/setup-cfg.ts
  src/updaters/python/setup-py.ts
  src/updaters/root-composer.ts
  src/updaters/samples-package-json.ts
  src/updaters/terraform/readme.ts
  src/updaters/update.ts
  src/updaters/version-rb.ts
  src/updaters/version-txt.ts
  src/updaters/version.ts
  test/releasers/java-yoshi.ts
  test/releasers/simple.ts
Labels: cla: yes

#445 docs: a significantly improved README
  .github/action/release-please/Dockerfile
  .github/action/release-please/LICENSE.txt
  .github/action/release-please/entrypoint.sh
  .readme-partials.yml
  README.md
  screen.png
  src/bin/release-please.ts
  synth.py
Labels: cla: yes
