Repository googleapis/release-please, pull requests merged in 2021-02, with the labels that each got.

#724 chore(go): cleanup unused code
  src/releasers/go-yoshi.ts
Labels: cla: yes

#729 chore: cleanup linter warnings
  src/releasers/go-yoshi.ts
Labels: cla: yes

#730 Revert "fix: use resolove to find imports in tests"
  src/github.ts
  test/github-release.ts
  test/release-pr-factory.ts
  test/release-pr.ts
  test/releasers/node.ts
  test/releasers/yoshi-go.ts
Labels: cla: yes

#727 chore: update CODEOWNERS config
  .repo-metadata.json
Labels: cla: yes

#720 feat!: support stable release branch names
  __snapshots__/github-release.js
  __snapshots__/github.js
  __snapshots__/java-yoshi.js
  __snapshots__/node.js
  __snapshots__/release-notes.js
  src/github-release.ts
  src/github.ts
  src/release-pr.ts
  src/releasers/go-yoshi.ts
  src/releasers/java-yoshi.ts
  src/releasers/node.ts
  src/releasers/ruby.ts
  src/util/branch-name.ts
  src/util/release-notes.ts
  test/fixtures/merged-pull-requests.json
  test/github-release.ts
  test/github.ts
  test/release-pr-factory.ts
  test/release-pr.ts
  test/releasers/node.ts
  test/releasers/yoshi-go.ts
  test/util/branch-name.ts
  test/util/package-branch-prefix.ts
  test/util/release-notes.ts
Labels: cla: yes

#733 test(go,java,node): convert yoshi-go, node tests to completely use sinon
  __snapshots__/node.js
  __snapshots__/yoshi-go.js
  test/releasers/fixtures/yoshi-go/cloud-go-commits.json
  test/releasers/fixtures/yoshi-go/discovery-commits.json
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
  test/releasers/node.ts
  test/releasers/utils.ts
  test/releasers/yoshi-go.ts
Labels: cla: yes

#725 feat(cli)!: refactor factory/CLI to be more testable
  __snapshots__/factory.js
  src/bin/release-please.ts
  src/factory.ts
  src/github-release.ts
  src/github.ts
  src/index.ts
  src/release-pr-factory.ts
  src/release-pr.ts
  test/cli.ts
  test/factory.ts
  test/github-release.ts
Labels: cla: yes

#736 fix!: remove deprecated JavaAuthYoshi releaser
  src/releasers/index.ts
  src/releasers/java-auth-yoshi.ts
Labels: cla: yes

#738 chore: use repo metadata to populate nodejs CODEOWNERS
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#737 refactor: use RELEASE_PLEASE for 'release-please'
  src/constants.ts
  src/github-release.ts
  src/github.ts
  src/index.ts
  src/release-pr.ts
  src/util/branch-name.ts
  test/util/branch-name.ts
Labels: cla: yes

#739 test: cleanup yoshi-php and factory tests
  __snapshots__/php-yoshi.js
  test/factory.ts
  test/release-pr.ts
  test/releasers/php-yoshi.ts
  test/releasers/utils.ts
Labels: automerge, cla: yes

#743 feat: allow explicitly empty packageName when creating a release
  __snapshots__/github.js
  src/github-release.ts
  src/github.ts
  test/github-release.ts
  test/github.ts
Labels: cla: yes

#742 refactor(github): unused GitHubPR properties
  src/github.ts
  src/release-pr.ts
Labels: cla: yes

#741 feat: add GitHub#commitsSince and GitHub#findMergeCommit
  __snapshots__/github.js
  src/github.ts
  test/fixtures/commits-since-page-1.json
  test/fixtures/commits-since-page-2.json
  test/fixtures/commits-since.json
  test/fixtures/latest-tag-alternate-branch.json
  test/fixtures/latest-tag-monorepo.json
  test/fixtures/latest-tag-no-commits.json
  test/fixtures/latest-tag.json
  test/github.ts
Labels: cla: yes

#750 refactor: graphql retries on 502 errors configurable in GitHub#graphqlRequest()
  __snapshots__/github.js
  src/github.ts
  test/github.ts
Labels: cla: yes

#751 feat: tagging the release also comments on the release PR
  __snapshots__/github.js
  src/github-release.ts
  src/github.ts
  test/fixtures/create-comment-response.json
  test/github-release.ts
  test/github.ts
Labels: cla: yes

#745 refactor: stricter releaseType typing
  .eslintrc.json
  src/bin/release-please.ts
  src/factory.ts
  src/github-release.ts
  src/index.ts
  src/release-pr.ts
  src/releasers/go-yoshi.ts
  src/releasers/index.ts
  src/releasers/java-bom.ts
  src/releasers/java-yoshi.ts
  src/releasers/node.ts
  src/releasers/ocaml.ts
  src/releasers/php-yoshi.ts
  src/releasers/python.ts
  src/releasers/ruby-yoshi.ts
  src/releasers/ruby.ts
  src/releasers/rust.ts
  src/releasers/simple.ts
  src/releasers/terraform-module.ts
  src/util/branch-name.ts
  synth.py
  test/cli.ts
  test/factory.ts
  test/github-release.ts
  test/release-pr.ts
  test/releasers/index.ts
  test/releasers/yoshi-go.ts
Labels: cla: yes

#752 refactor: commit-split enhancements
  src/commit-split.ts
  src/github.ts
  test/commit-split.ts
  test/helpers.ts
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
  test/releasers/node.ts
  test/releasers/utils.ts
  test/releasers/yoshi-go.ts
Labels: cla: yes

#754 refactor: getFileContentsWithSimpleAPI with commit
  src/github.ts
  test/github.ts
Labels: cla: yes

#759 feat: add async interator for searching commit history
  src/github.ts
Labels: cla: yes

#755 refactor: releaser interface for aggregate
  __snapshots__/python.js
  src/release-pr.ts
  src/releasers/node.ts
  src/releasers/python.ts
  test/releasers/node.ts
  test/releasers/python.ts
  test/releasers/utils.ts
Labels: cla: yes

#758 refactor!: move latestTag logic to ReleasePR
  src/github.ts
  src/release-pr.ts
  src/releasers/go-yoshi.ts
  src/releasers/java-bom.ts
  src/releasers/java-yoshi.ts
  src/releasers/node.ts
  src/releasers/ocaml.ts
  src/releasers/php-yoshi.ts
  src/releasers/python.ts
  src/releasers/ruby.ts
  src/releasers/rust.ts
  src/releasers/simple.ts
  src/releasers/terraform-module.ts
  test/fixtures/latest-tag-stable-branch.json
  test/github.ts
  test/release-pr.ts
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
  test/releasers/node.ts
  test/releasers/ocaml.ts
  test/releasers/php-yoshi.ts
  test/releasers/python.ts
  test/releasers/rust.ts
  test/releasers/simple.ts
  test/releasers/terraform-module.ts
  test/releasers/yoshi-go.ts
Labels: cla: yes

#762 refactor: squash helper method into ReleasePR.latestTag
  src/release-pr.ts
Labels: cla: yes

#765 feat: add latest-tag command which will print out the detected latest tag
  src/bin/release-please.ts
Labels: cla: yes

#764 fix: find first associate pull request
  src/github.ts
Labels: cla: yes

#757 fix(github-release): release name is packageName
  __snapshots__/github-release.js
  src/github-release.ts
  src/github.ts
  src/release-pr.ts
  test/github-release.ts
Labels: automerge, cla: yes

#748 feat: add support for helm
  .gitignore
  README.md
  __snapshots__/chart-yaml.js
  package.json
  src/releasers/helm.ts
  src/releasers/index.ts
  src/updaters/helm/chart-yaml.ts
  test/cli.ts
  test/updaters/chart-yaml.ts
  test/updaters/fixtures/helm/Chart.yaml
Labels: cla: yes

#763 refactor!: normalize configuration across classes
  src/bin/release-please.ts
  src/constants.ts
  src/conventional-commits.ts
  src/factory.ts
  src/github-release.ts
  src/github.ts
  src/index.ts
  src/release-pr.ts
  src/releasers/go-yoshi.ts
  src/releasers/helm.ts
  src/releasers/index.ts
  src/releasers/java-bom.ts
  src/releasers/java-yoshi.ts
  src/releasers/node.ts
  src/releasers/ocaml.ts
  src/releasers/php-yoshi.ts
  src/releasers/python.ts
  src/releasers/ruby-yoshi.ts
  src/releasers/ruby.ts
  src/releasers/rust.ts
  src/releasers/simple.ts
  src/releasers/terraform-module.ts
  test/cli.ts
  test/conventional-commits.ts
  test/factory.ts
  test/github-release.ts
  test/release-pr.ts
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
  test/releasers/node.ts
  test/releasers/ocaml.ts
  test/releasers/php-yoshi.ts
  test/releasers/python.ts
  test/releasers/rust.ts
  test/releasers/simple.ts
  test/releasers/terraform-module.ts
  test/releasers/yoshi-go.ts
Labels: cla: yes

#769 chore: helm test case
  __snapshots__/helm.js
  test/releasers/fixtures/helm/Chart.yaml
  test/releasers/helm/helm.ts
Labels: cla: yes

#767 refactor!: rename factory.run -> call
  .mocharc.js
  src/bin/release-please.ts
  src/factory.ts
  src/github-release.ts
  test/cli.ts
  test/factory.ts
Labels: cla: yes

#770 refactor!: move fork down to GitHub
  src/bin/release-please.ts
  src/constants.ts
  src/factory.ts
  src/github.ts
  src/index.ts
  src/release-pr.ts
  src/releasers/index.ts
  synth.py
  test/factory.ts
  test/github.ts
Labels: cla: yes

#773 refactor: helper/util tweaks to DRY out test code
  __snapshots__/node.js
  src/releasers/python.ts
  test/helpers.ts
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
  test/releasers/node.ts
  test/releasers/python.ts
  test/releasers/utils.ts
Labels: cla: yes

#776 fix(release-pr): update default initial version
  __snapshots__/node.js
  src/release-pr.ts
  test/releasers/node.ts
Labels: cla: yes

#780 feat: pull request title resource
  src/release-pr.ts
  src/releasers/java-yoshi.ts
  src/util/pull-request-title.ts
  test/fixtures/latest-tag-renamed.json
  test/releasers/java-yoshi.ts
  test/util/pull-request-title.ts
Labels: cla: yes

#781 fix: only add the target branch to PR title for non-default branches
  src/github.ts
  src/releasers/java-yoshi.ts
  test/releasers/java-yoshi.ts
Labels: cla: yes

#785 refactor(manifest): code layout, file format
  src/constants.ts
  src/index.ts
  src/manifest.ts
  src/util/checkpoint.ts
  test/manifest.ts
Labels: cla: yes

#779 docs: document correct version of action
  README.md
Labels: cla: yes

#782 fix: do not change format of Python version files
  __snapshots__/python.js
  __snapshots__/version-py.js
  src/updaters/python/setup-cfg.ts
  src/updaters/python/setup-py.ts
  src/updaters/python/version-py.ts
  test/updaters/fixtures/version.py
Labels: cla: yes

#787 refactor: snapshot cleanup and ordering
  __snapshots__/cargo-lock.js
  __snapshots__/changelog.js
  __snapshots__/conventional-commits.js
  __snapshots__/github.js
  __snapshots__/helm.js
  __snapshots__/indent-commit.js
  __snapshots__/java-auth-readme.js
  __snapshots__/java-auth-versions.js
  __snapshots__/java-bom.js
  __snapshots__/java-yoshi.js
  __snapshots__/node.js
  __snapshots__/ocaml.js
  __snapshots__/php-yoshi.js
  __snapshots__/pom-xml.js
  __snapshots__/python.js
  __snapshots__/release-notes.js
  __snapshots__/rust.js
  __snapshots__/samples-package-json.js
  __snapshots__/simple.js
  __snapshots__/terraform-module.js
  __snapshots__/yoshi-go.js
  package.json
  src/release-pr.ts
  test/helpers.ts
  test/releasers/helm/helm.ts
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
  test/releasers/node.ts
  test/releasers/ocaml.ts
  test/releasers/php-yoshi.ts
  test/releasers/python.ts
  test/releasers/rust.ts
  test/releasers/simple.ts
  test/releasers/terraform-module.ts
  test/releasers/yoshi-go.ts
Labels: cla: yes

#789 feat: expose the release body to consumers
  src/github-release.ts
  src/github.ts
  src/manifest.ts
  test/factory.ts
  test/github-release.ts
Labels: cla: yes

#791 fix(pagination): looking for pending PRs had no pagination limit
  src/release-pr.ts
  test/release-pr.ts
Labels: cla: yes

#790 refactor: move changelogPath down to ReleasePR
  __snapshots__/python.js
  __snapshots__/ruby.js
  src/factory.ts
  src/github-release.ts
  src/index.ts
  src/release-pr.ts
  src/releasers/go-yoshi.ts
  src/releasers/helm.ts
  src/releasers/java-bom.ts
  src/releasers/java-yoshi.ts
  src/releasers/node.ts
  src/releasers/ocaml.ts
  src/releasers/php-yoshi.ts
  src/releasers/python.ts
  src/releasers/ruby.ts
  src/releasers/rust.ts
  src/releasers/simple.ts
  src/releasers/terraform-module.ts
  test/cli.ts
  test/factory.ts
  test/github-release.ts
  test/releasers/fixtures/ruby/version.rb
  test/releasers/python.ts
  test/releasers/ruby.ts
Labels: cla: yes

#792 fix: js-yaml should be a dependency not devDependency
  package.json
Labels: cla: yes

#795 fix: bug in Terraform version updater
  __snapshots__/terraform-module.js
  src/updaters/terraform/module-version.ts
  test/releasers/fixtures/terraform/simple-module/readme.md
  test/releasers/fixtures/terraform/simple-module/versions.tf
  test/releasers/terraform-module.ts
Labels: cla: yes

#784 feat: support custom pull request title
  README.md
  src/bin/release-please.ts
  src/index.ts
  src/release-pr.ts
  src/util/pull-request-title.ts
  test/cli.ts
  test/util/pull-request-title.ts
Labels: cla: yes

#799 build: ignore .mocharc.js
  synth.py
Labels: cla: yes

#801 refactor: commit split only needs / sep
  src/commit-split.ts
  test/commit-split.ts
Labels: cla: yes

#800 refactor(manifest): pullRequest implementation
  __snapshots__/manifest.js
  src/github.ts
  src/graphql-to-commits.ts
  src/manifest.ts
  src/updaters/release-please-manifest.ts
  test/fixtures/manifest/repo/node/pkg1/package.json
  test/fixtures/manifest/repo/node/pkg2/package.json
  test/fixtures/manifest/repo/python/setup.cfg
  test/fixtures/manifest/repo/python/setup.py
  test/fixtures/manifest/repo/python/src/foolib/version.py
  test/github.ts
  test/manifest.ts
Labels: cla: yes

#803 fix(node): PackageJson updater sets this.contents
  src/github.ts
  src/updaters/package-json.ts
  test/github.ts
  test/releasers/node.ts
Labels: cla: yes
