Repository googleapis/release-please, pull requests merged in 2021-05, with the labels that each got.

#890 feat: add generic go releaser
  __snapshots__/go.js
  src/releasers/go.ts
  src/releasers/index.ts
  test/releasers/go.ts
Labels: automerge, cla: yes

#884 feat: add custom logger interface
  __snapshots__/go.js
  __snapshots__/helm.js
  __snapshots__/java-bom.js
  __snapshots__/java-lts.js
  __snapshots__/java-yoshi.js
  __snapshots__/manifest.js
  __snapshots__/node.js
  __snapshots__/ocaml.js
  __snapshots__/php-yoshi.js
  __snapshots__/python.js
  __snapshots__/ruby.js
  __snapshots__/rust.js
  __snapshots__/simple.js
  __snapshots__/terraform-module.js
  __snapshots__/yoshi-go.js
  package.json
  src/conventional-commits.ts
  src/github-release.ts
  src/github.ts
  src/index.ts
  src/release-pr.ts
  src/releasers/go-yoshi.ts
  src/releasers/java-yoshi.ts
  src/releasers/php-yoshi.ts
  src/releasers/ruby-yoshi.ts
  src/releasers/rust.ts
  src/updaters/changelog.ts
  src/updaters/helm/chart-yaml.ts
  src/updaters/ocaml/dune-project.ts
  src/updaters/ocaml/esy-json.ts
  src/updaters/ocaml/opam.ts
  src/updaters/package-json.ts
  src/updaters/php-manifest.ts
  src/updaters/root-composer.ts
  src/updaters/rust/cargo-lock.ts
  src/updaters/rust/cargo-toml.ts
  src/updaters/samples-package-json.ts
  src/updaters/terraform/module-version.ts
  src/util/checkpoint.ts
  src/util/logger.ts
Labels: cla: yes

#894 feat(python): support pyproject.toml
  README.md
  __snapshots__/pyproject-toml.js
  __snapshots__/pyproject.js
  __snapshots__/python-file-with-version.js
  __snapshots__/python.js
  src/releasers/python.ts
  src/updaters/python/pyproject-toml.ts
  src/updaters/python/python-file-with-version.ts
  src/updaters/rust/cargo-lock.ts
  src/updaters/rust/cargo-toml.ts
  src/updaters/toml-edit.ts
  test/fixtures/manifest/repo/python/src/__init__.py
  test/manifest.ts
  test/releasers/python.ts
  test/updaters/fixtures/__init__.py
  test/updaters/fixtures/project/__init__.py
  test/updaters/fixtures/pyproject-poetry.toml
  test/updaters/fixtures/pyproject-project.toml
  test/updaters/fixtures/pyproject.toml
  test/updaters/pyproject-toml.ts
  test/updaters/python-file-with-version.ts
  test/util/toml-edit.ts
Labels: cla: yes

#900 feat: allow overriding release label
  src/github-release.ts
  src/index.ts
  test/github-release.ts
Labels: cla: yes

#901 fix(manifest): node-workspace plugin respects release-as
  __snapshots__/node-workspace.js
  src/factory.ts
  src/github.ts
  src/manifest.ts
  src/plugins/node-workspace.ts
  src/release-pr.ts
  src/releasers/java-bom.ts
  src/releasers/java-yoshi.ts
  src/updaters/java/java_update.ts
  src/util/branch-name.ts
  test/cli.ts
  test/commit-split.ts
  test/factory.ts
  test/plugins/node-workspace.ts
Labels: automerge, cla: yes

#907 build: remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: full

#910 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#912 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
  synth.py
Labels: cla: yes

#917 fix: update simple releaser for monorepo pkg path
  src/releasers/simple.ts
Labels: cla: yes
