Repository googleapis/release-please, pull requests merged in 2021-09, with the labels that each got.

#1030 feat: add elixir updater and releaser
  README.md
  __snapshots__/cli.js
  __snapshots__/elixir-mix-exs.js
  __snapshots__/elixir.js
  src/releasers/elixir.ts
  src/releasers/index.ts
  src/updaters/elixir-mix-exs.ts
  test/cli.ts
  test/releasers/elixir.ts
  test/releasers/fixtures/elixir/mix.exs
  test/updaters/elixir-mix-exs.ts
  test/updaters/fixtures/mix.exs
Labels: cla: yes, automerge: exact

#1041 fix(ruby): The Ruby releaser defaults to the correct version.rb path
  __snapshots__/ruby.js
  src/releasers/ruby.ts
  test/releasers/ruby.ts
Labels: cla: yes

#1026 feat(python): support packagename/__init__.py without pyproject.toml
  src/releasers/python.ts
  test/manifest.ts
  test/releasers/python.ts
Labels: cla: yes

#1044 chore: switch to main branch
  .github/sync-repo-settings.yaml
  README.md
Labels: cla: yes

#1050 fix: typo in `--bump-patch-for-minor-pre-major` option
  __snapshots__/cli.js
  src/bin/release-please.ts
Labels: cla: yes

#1036 feat(manifest)!: force local linking in node-workspaces w/ config to disable
  __snapshots__/node-workspace.js
  docs/manifest-releaser.md
  src/manifest.ts
  src/plugins/node-workspace.ts
  test/plugins/node-workspace.ts
  typings/lerna__package-graph.d.ts
Labels: cla: yes

#1065 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, automerge

#1061 fix: add missing comma at EOL for mix exs version
  __snapshots__/elixir-mix-exs.js
  __snapshots__/elixir.js
  src/updaters/elixir-mix-exs.ts
Labels: cla: yes

#1060 feat: github-release can customize the label applied to the pull request
  __snapshots__/cli.js
  src/bin/release-please.ts
Labels: cla: yes, automerge

#1033 feat: add signoff options to sign off commits
  README.md
  __snapshots__/cli.js
  src/bin/release-please.ts
  src/github.ts
  src/index.ts
  src/manifest.ts
  src/release-pr.ts
  src/util/signoff-commit-message.ts
  test/cli.ts
  test/util/signoff-commit-message.ts
Labels: cla: yes

#1048 feat(manifest): add option to skip creating github release
  docs/manifest-releaser.md
  src/index.ts
  src/manifest.ts
  test/manifest.ts
Labels: cla: yes

#1070 feat: allow forcing latest tag
  __snapshots__/cli.js
  src/bin/release-please.ts
  src/factory.ts
  src/index.ts
  src/release-pr.ts
Labels: cla: yes

#1062 feat(python): support src/packagename/__init__.py
  __snapshots__/python-file-with-version.js
  __snapshots__/python.js
  src/releasers/python.ts
  test/fixtures/manifest/repo/python/src/foolib/__init__.py
  test/manifest.ts
  test/releasers/python.ts
  test/updaters/fixtures/src/project/__init__.py
  test/updaters/python-file-with-version.ts
Labels: cla: yes

#1053 feat: add dart updater and releaser
  README.md
  __snapshots__/cli.js
  __snapshots__/dart.js
  __snapshots__/pubspec-yaml.js
  src/releasers/dart.ts
  src/releasers/index.ts
  src/updaters/pubspec-yaml.ts
  test/cli.ts
  test/releasers/dart.ts
  test/releasers/fixtures/dart/pubspec.yaml
  test/updaters/fixtures/pubspec.yaml
  test/updaters/fixtures/pubspec_with_build_no.yaml
  test/updaters/pubspec-yaml.ts
Labels: cla: yes

#1074 feat: add java-backport releaser
  __snapshots__/cli.js
  __snapshots__/java-backport.js
  src/releasers/index.ts
  src/releasers/java-backport.ts
  test/cli.ts
  test/releasers/java-backport.ts
Labels: cla: yes
