Repository googleapis/release-please, pull requests merged in 2021-04, with the labels that each got.

#847 feat: allow "standard" pre-1.0.0 patch bumps
  __snapshots__/cli.js
  docs/manifest-releaser.md
  src/bin/release-please.ts
  src/conventional-commits.ts
  src/index.ts
  src/manifest.ts
  src/release-pr.ts
  src/releasers/node.ts
  src/releasers/python.ts
  test/conventional-commits.ts
Labels: cla: yes

#848 fix(manifest): package paths sharing same prefix being shadowed in commit-split
  src/commit-split.ts
  test/commit-split.ts
Labels: cla: yes

#850 feat: add ability to specify extra files for releasers to consider
  __snapshots__/java-yoshi.js
  package.json
  src/index.ts
  src/release-pr.ts
  src/releasers/java-yoshi.ts
  test/releasers/fixtures/java-yoshi/Version.java
  test/releasers/java-yoshi.ts
Labels: cla: yes

#844 feat(manifest): node workspace package dependency updates
  __snapshots__/manifest.js
  __snapshots__/node-workspace.js
  docs/manifest-releaser.md
  package.json
  src/github.ts
  src/index.ts
  src/manifest.ts
  src/plugins/index.ts
  src/plugins/node-workspace.ts
  src/plugins/plugin.ts
  src/updaters/package-json.ts
  src/util/package-json-stringify.ts
  test/fixtures/manifest/repo/node/pkg2/package.json
  test/manifest.ts
  test/plugins/node-workspace.ts
  typings/lerna__collect-updates.d.ts
  typings/lerna__package-graph.d.ts
  typings/lerna__package.d.ts
  typings/lerna__run-topologically.d.ts
Labels: cla: yes

#859 refactor: move simple-case process into base ReleasePR class
  src/release-pr.ts
  src/releasers/helm.ts
  src/releasers/java-yoshi.ts
  src/releasers/node.ts
  src/releasers/ocaml.ts
  src/releasers/simple.ts
  src/releasers/terraform-module.ts
Labels: cla: yes

#861 refactor: simplify ruby releaser
  src/release-pr.ts
  src/releasers/ruby.ts
Labels: cla: yes

#867 fix(ocaml): Improve OCaml releaser for monorepos
  __snapshots__/dune-project.js
  __snapshots__/ocaml.js
  src/releasers/ocaml.ts
  src/updaters/ocaml/dune-project.ts
  test/updaters/dune-project.ts
  test/updaters/fixtures/dune-project
Labels: cla: yes

#857 fix: adjust patch rule for Java LTS strategy
  __snapshots__/java-lts.js
  docs/java-releases.md
  src/releasers/java-lts.ts
  src/releasers/java/bump_type.ts
  src/releasers/java/version.ts
  src/updaters/java/versions-manifest.ts
  test/releasers/fixtures/java-yoshi/released-lts-versions.txt
  test/releasers/fixtures/java-yoshi/versions-lts-snapshot.txt
  test/releasers/java-lts.ts
  test/releasers/java/version.ts
Labels: cla: yes

#863 build: switch to $default_branch remove unused secrets
  .github/workflows/ci.yaml
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes, context: full

#868 deps: lerna 4.0.0 upgrade
  package.json
  src/plugins/node-workspace.ts
  typings/lerna__package-graph.d.ts
  typings/lerna__package.d.ts
  typings/lerna__run-topologically.d.ts
Labels: cla: yes

#880 fix(octokit): address regression in internal octokit types
  src/github.ts
Labels: cla: yes

#875 chore: add sync repo settings config
  .github/sync-repo-settings.yaml
Labels: automerge: exact, cla: yes

#874 fix: Java replacer should handle `-sp.1` version replacements
  __snapshots__/java-update.js
  src/updaters/java/java_update.ts
  test/updaters/fixtures/pom-java-lts-snapshot.xml
  test/updaters/java-update.ts
Labels: automerge, cla: yes

#871 fix(manifest): dynamic importing does not work with build for action
  src/manifest.ts
  src/plugins/index.ts
Labels: cla: yes

#872 docs: Add more detail around release process
  README.md
Labels: cla: yes

#888 build: warn uses when they edit auto-generated files
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#891 fix(release-as): commits with Release-As footer now create release
  __snapshots__/conventional-commits.js
  package.json
  src/util/to-conventional-changelog-format.ts
  test/conventional-commits.ts
Labels: cla: yes
