Repository googleapis/release-please, pull requests merged in 2021-01, with the labels that each got.

#680 chore: disable header check for snapshots
  .github/header-checker-lint.yml
Labels: cla: yes

#677 docs: update contributing guide
  CONTRIBUTING.md
  package.json
  synth.py
Labels: cla: yes

#674 refactor: migrate to @conventional-commits/parser and update conventional-changelog
  __snapshots__/yoshi-go.js
  package.json
  src/conventional-commits.ts
  test/helpers.ts
  test/releasers/yoshi-go.ts
Labels: cla: yes

#673 feat: support @ and / when falling back to tags
  src/github.ts
  src/releasers/go-yoshi.ts
  src/releasers/ruby.ts
  test/github.ts
Labels: cla: yes

#684 feat: add rust releaser & cargo-toml updater
  __snapshots__/cargo-toml.js
  __snapshots__/rust.js
  package.json
  src/releasers/index.ts
  src/releasers/rust.ts
  src/updaters/cargo-toml.ts
  test/releasers/fixtures/rust/Cargo-crate1.toml
  test/releasers/fixtures/rust/Cargo-crate2.toml
  test/releasers/fixtures/rust/Cargo-workspace.toml
  test/releasers/rust.ts
  test/updaters/cargo-toml.ts
  test/updaters/fixtures/Cargo.toml
Labels: cla: yes

#682 refactor: copy toConventionalChangelogFormat from conventional-commits
  package.json
  src/conventional-commits.ts
  src/util/to-conventional-changelog-format.ts
Labels: cla: yes

#665 fix: `findFilesByfilename` respects `path` option
  src/github.ts
  src/releasers/python.ts
  test/fixtures/pom-file-search-with-prefix.json
  test/github.ts
Labels: cla: yes

#686 feat!: support multiple commits in footer
  README.md
  __snapshots__/conventional-commits.js
  package.json
  src/conventional-commits.ts
  src/util/to-conventional-changelog-format.ts
  test/conventional-commits.ts
Labels: cla: yes

#669 fix(monorepos): github-release not created
  __snapshots__/github-release.js
  src/github-release.ts
  src/github.ts
  src/release-pr.ts
  src/releasers/node.ts
  src/util/package-branch-prefix.ts
  test/github-release.ts
  test/release-pr.ts
  test/releasers/node.ts
  test/util/package-branch-prefix.ts
Labels: automerge, cla: yes

#694 feat: add addFilesByExtension method & allow leading slash in path
  __snapshots__/github.js
  src/github.ts
  src/release-pr.ts
  test/github.ts
Labels: cla: yes

#698 fix(github-release): increasae page size finding release
  src/github-release.ts
  test/github-release.ts
Labels: cla: yes

#697 feat: add ocaml releaser and esy/opam updaters
  README.md
  __snapshots__/esy-json.js
  __snapshots__/github.js
  __snapshots__/ocaml.js
  __snapshots__/opam.js
  src/releasers/index.ts
  src/releasers/ocaml.ts
  src/updaters/ocaml/esy-json.ts
  src/updaters/ocaml/opam.ts
  test/helpers.ts
  test/releasers/fixtures/ocaml/esy.json
  test/releasers/fixtures/ocaml/sample.opam
  test/releasers/ocaml.ts
  test/updaters/esy-json.ts
  test/updaters/fixtures/esy.json
  test/updaters/fixtures/sample.opam
  test/updaters/opam.ts
Labels: cla: yes

#702 chore: update test snapshots
  .eslintignore
  __snapshots__/commit-split.js
  __snapshots__/github-release.js
  __snapshots__/github.js
  __snapshots__/graphql-to-commits.js
  __snapshots__/java-bom.js
  __snapshots__/java-yoshi.js
  __snapshots__/node.js
  __snapshots__/yoshi-go.js
Labels: cla: yes

#706 fix: return PRs by last updated
  src/github.ts
  test/github-release.ts
  test/github.ts
  test/release-pr-factory.ts
  test/release-pr.ts
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
  test/releasers/node.ts
  test/releasers/yoshi-go.ts
Labels: cla: yes

#708 fix(pagination): when tagging release, use updated, vs., created
  src/github-release.ts
  src/github.ts
  test/github.ts
  test/release-pr-factory.ts
  test/release-pr.ts
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
  test/releasers/node.ts
  test/releasers/yoshi-go.ts
Labels: cla: yes

#712 feat: add add GitHub helpers for findFilesByFilenameAndRef and findFilesByExtensionAndRef
  __snapshots__/java-yoshi.js
  src/github.ts
  test/fixtures/pom-file-search-with-prefix.json
  test/fixtures/pom-file-search.json
  test/github.ts
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
Labels: cla: yes

#711 fix(go): support processing footers in gapics
  __snapshots__/yoshi-go.js
  src/conventional-commits.ts
  src/releasers/go-yoshi.ts
  test/releasers/fixtures/yoshi-go/cloud-go-commits.json
Labels: cla: yes

#703 feat(github-release): create a draft release
  __snapshots__/github-release.js
  src/bin/release-please.ts
  src/github-release.ts
  src/github.ts
  test/github-release.ts
Labels: cla: yes

#717 test(java): convert Java releaser tests to use sinon
  __snapshots__/github.js
  __snapshots__/java-bom.js
  __snapshots__/java-yoshi.js
  src/release-pr.ts
  test/github.ts
  test/releasers/java-bom.ts
  test/releasers/java-yoshi.ts
Labels: cla: yes

#715 fix: use resolove to find imports in tests
  src/github.ts
  test/github-release.ts
  test/release-pr-factory.ts
  test/release-pr.ts
  test/releasers/node.ts
  test/releasers/yoshi-go.ts
Labels: cla: yes

#721 refactor(nodejs): move build cop to flakybot
  .kokoro/samples-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#722 chore: remove unused constant
  src/releasers/go-yoshi.ts
Labels: automerge, cla: yes
