Repository googleapis/release-please, pull requests merged in 2022-04, with the labels that each got.

#1361 fix: Restore v12 changelog formatting for ruby-yoshi
  __snapshots__/ruby-yoshi.js
  src/strategies/ruby-yoshi.ts
  test/strategies/ruby-yoshi.ts
Labels: automerge, size: m

#1364 chore: update ci to test node 16 rather than node 15
  .github/workflows/ci.yaml
Labels: size: xs

#1370 chore: update required check from node 15 -> 16
  .github/sync-repo-settings.yaml
Labels: automerge, size: xs

#1369 chore: remove unused legacy config
  .bots/header-checker-lint.json
Labels: automerge, size: xs

#1362 feat: support selecting a single path when releasing from a manifest
  src/bin/release-please.ts
  src/manifest.ts
  test/cli.ts
  test/manifest.ts
Labels: automerge, size: m

#1374 fix: update Cargo.lock for single Rust crate
  src/strategies/rust.ts
  test/fixtures/strategies/rust-workspace/Cargo-crate1.toml
  test/fixtures/strategies/rust-workspace/Cargo-crate2.toml
  test/fixtures/strategies/rust-workspace/Cargo-workspace.toml
  test/fixtures/strategies/rust-workspace/Cargo.lock
  test/fixtures/strategies/rust/Cargo.lock
  test/fixtures/strategies/rust/Cargo.toml
  test/strategies/rust.ts
Labels: size: m

#1378 fix: fixed maxResults check in tag and release iterators
  src/github.ts
Labels: automerge, size: xs

#1377 fix: bump retries for pull request iterator from 1 to 3
  src/github.ts
Labels: size: s

#1386 fix(java): snapshots should bump versionsMap versions
  src/strategies/base.ts
  src/strategies/java.ts
  test/strategies/java-yoshi.ts
Labels: automerge, size: s

#1384 feat(cli): show file diff for release-pr command with --dry-run and --trace
  package.json
  src/bin/release-please.ts
  src/github.ts
Labels: automerge, size: s

#1342 feat: extensible factories
  __snapshots__/cli.js
  src/factories/changelog-notes-factory.ts
  src/factories/plugin-factory.ts
  src/factories/versioning-strategy-factory.ts
  src/factory.ts
  src/index.ts
  src/manifest.ts
  src/strategies/base.ts
  src/strategies/java.ts
  src/strategies/ruby-yoshi.ts
  src/strategies/ruby.ts
  src/strategies/simple.ts
  test/factories/changelog-notes-factory.ts
  test/factories/plugin-factory.ts
  test/factories/versioning-strategy-factory.ts
  test/factory.ts
  test/manifest.ts
Labels: automerge: exact, size: l

#1393 fix(deps): switch from `xmldom` to `@xmldom/xmldom` and update to v0.8.2
  package.json
  src/updaters/base-xml.ts
Labels: automerge, size: xs

#1397 fix: Allow an empty value for --label
  src/bin/release-please.ts
  test/cli.ts
Labels: automerge, size: s

#1396 feat: allow configuring `release-search-depth` and `commit-search-depth`
  docs/manifest-releaser.md
  src/manifest.ts
  test/fixtures/manifest/config/search-depth.json
  test/helpers.ts
  test/manifest.ts
Labels: automerge, size: m

#1399 feat: add a flag to disable adding labels to new pull requests
  __snapshots__/cli.js
  docs/cli.md
  src/bin/release-please.ts
  src/github.ts
  src/manifest.ts
  test/cli.ts
Labels: automerge, size: s

#1401 feat: Support sequential-calls manifest field that disables concurrency when creating multiple pull requests or releases
  docs/cli.md
  docs/manifest-releaser.md
  src/manifest.ts
Labels: automerge, size: m

#1405 chore: skip sync-repo-settings from templates
  owlbot.py
Labels: size: xs

#1408 feat: allow configure changelog-host
  __snapshots__/base.js
  __snapshots__/cli.js
  docs/cli.md
  docs/manifest-releaser.md
  src/bin/release-please.ts
  src/manifest.ts
  src/strategies/base.ts
  src/strategies/php-yoshi.ts
  test/cli.ts
  test/fixtures/manifest/config/changelog-host.json
  test/manifest.ts
  test/strategies/base.ts
Labels: size: m
