Repository googleapis/release-please, pull requests merged in 2022-07, with the labels that each got.

#1508 docs(readme): remove synthtool warning
  README.md
Labels: size: xs

#1506 docs(readme): fix wording, spacing, case
  README.md
Labels: size: s

#1509 chore: remove generated-files-bot warnings for README.md
  .github/generated-files-bot.yml
  owlbot.py
Labels: size: xs

#1512 fix: move schemas to their own directory and add to dist
  package.json
  schemas/config.json
  schemas/manifest.json
  src/index.ts
Labels: automerge, size: xs

#1518 fix: stop iterating if we fail to receive commits from a graphql query
  src/github.ts
Labels: size: m

#1526 fix(python): Make __init__.py bump underscore / hyphen agnostic (#1525)
  src/strategies/python.ts
  test/strategies/python.ts
Labels: size: s

#1524 fix(dart): Add multiline flag to replace regex
  __snapshots__/pubspec-yaml.js
  src/updaters/dart/pubspec-yaml.ts
  test/updaters/fixtures/pubspec_with_build_no_bad.yaml
  test/updaters/pubspec-yaml.ts
Labels: size: m

#1537 fix: skip component when manifest release does not include component
  src/strategies/base.ts
  test/fixtures/release-notes/grouped.txt
  test/manifest.ts
Labels: automerge, size: m
