Repository googleapis/release-please, pull requests merged in 2022-09, with the labels that each got.

#1628 fix(sentence-case): handle multiple : in subject
  src/plugins/sentence-case.ts
  test/plugins/sentence-case.ts
Labels: size: s

#1627 fix: allow parentheses in `pull-request-title-pattern`
  src/util/pull-request-title.ts
  test/util/pull-request-title.ts
Labels: size: xs

#1630 feat: update elixir version in module attribute
  __snapshots__/elixir-mix-exs.js
  src/updaters/elixir/elixir-mix-exs.ts
  test/updaters/elixir-mix-exs.ts
  test/updaters/fixtures/mix-attribute.exs
Labels: size: m

#1621 feat: allow specifying glob option for extra-files
  package.json
  schemas/config.json
  src/github.ts
  src/manifest.ts
  src/strategies/base.ts
  src/strategies/java.ts
  test/fixtures/manifest/config/extra-files-glob.json
  test/strategies/base.ts
Labels: automerge, size: m

#1566 feat: allow nesting multiple commits that are parsed independently
  src/commit.ts
  test/commits.ts
  test/fixtures/commit-messages/multiple-commits-with-separator.txt
Labels: size: m

#1644 fix: detect uppercase readme.md files for TF
  src/strategies/terraform-module.ts
  test/strategies/terraform-module.ts
Labels: size: s

#1638 fix: detect overlaping prefixes
  src/util/commit-split.ts
  test/util/commit-split.ts
Labels: size: s

#1639 feat: Easy proxy configuration
  package.json
  src/github.ts
  test/github.ts
  tsconfig.json
Labels: size: m

#1651 fix: handle pull request files returned as null
  __snapshots__/github.js
  src/github.ts
  test/fixtures/commits-since-no-files.json
  test/github.ts
Labels: size: m

#1652 fix(node): rethrow missing file error for package.json as a configuration error
  src/strategies/node.ts
  test/strategies/node.ts
Labels: size: s

#1655 fix: graphql proxy connection issue
  src/github.ts
Labels: size: xs

#1661 fix: escape html tags in release notes
  __snapshots__/default-changelog-notes.js
  src/changelog-notes/default.ts
  test/changelog-notes/default-changelog-notes.ts
Labels: size: s

#1660 feat: add `group-priority` plugin
  docs/manifest-releaser.md
  schemas/config.json
  src/factories/plugin-factory.ts
  src/manifest.ts
  src/plugins/group-priority.ts
  src/release-pull-request.ts
  src/strategies/base.ts
  src/strategies/java.ts
  test/factories/plugin-factory.ts
  test/fixtures/manifest/config/group-priority.json
  test/helpers.ts
  test/plugins/cargo-workspace.ts
  test/plugins/group-priority.ts
  test/plugins/maven-workspace.ts
  test/plugins/merge.ts
  test/plugins/node-workspace.ts
Labels: size: l

#1665 feat: add initial version to base strategy
  __snapshots__/base.js
  schemas/config.json
  src/manifest.ts
  src/strategies/base.ts
  test/strategies/base.ts
Labels: size: s

#1669 feat: add ability to set extra labels on components
  schemas/config.json
  src/manifest.ts
  src/strategies/base.ts
  src/strategies/java.ts
  src/strategies/php-yoshi.ts
  test/fixtures/manifest/config/extra-labels.json
  test/manifest.ts
  test/strategies/base.ts
Labels: automerge, size: m

#1670 fix: manifest config bootstrapper should include schema field
  src/bin/release-please.ts
  src/bootstrapper.ts
  src/updaters/release-please-manifest.ts
Labels: size: m

#1671 feat(cli): add debug command for loading a manifest config
  src/bin/release-please.ts
  src/manifest.ts
  src/plugins/linked-versions.ts
  test/manifest.ts
Labels: automerge, size: m
