Repository googleapis/release-please, pull requests merged in 2022-10, with the labels that each got.

#1678 fix: put config schema on correct file
  __snapshots__/bootstrapper.js
  src/updaters/release-please-config.ts
  src/updaters/release-please-manifest.ts
Labels: size: s

#1680 fix(maven-workspace): preserve original pom.xml updater when bumping dependencies
  __snapshots__/maven-workspace.js
  src/plugins/maven-workspace.ts
  test/plugins/maven-workspace.ts
Labels: size: m

#1667 feat(maven-workspace): update all discovered pom.xml within the components
  __snapshots__/maven-workspace.js
  docs/manifest-releaser.md
  schemas/config.json
  src/factories/plugin-factory.ts
  src/manifest.ts
  src/plugins/maven-workspace.ts
  src/plugins/workspace.ts
  src/util/logger.ts
  test/factories/plugin-factory.ts
  test/fixtures/manifest/config/maven-workspace-plugins.json
  test/fixtures/plugins/maven-workspace/bom/pom.xml
  test/fixtures/plugins/maven-workspace/multi1/bom/pom.xml
  test/fixtures/plugins/maven-workspace/multi1/pom.xml
  test/fixtures/plugins/maven-workspace/multi1/primary/pom.xml
  test/fixtures/plugins/maven-workspace/multi1/sub1/pom.xml
  test/fixtures/plugins/maven-workspace/multi1/sub2/pom.xml
  test/fixtures/plugins/maven-workspace/multi2/bom/pom.xml
  test/fixtures/plugins/maven-workspace/multi2/pom.xml
  test/fixtures/plugins/maven-workspace/multi2/primary/pom.xml
  test/fixtures/plugins/maven-workspace/multi2/sub1/pom.xml
  test/fixtures/plugins/maven-workspace/multi2/sub2/pom.xml
  test/manifest.ts
  test/plugins/maven-workspace.ts
Labels: size: l

#1685 fix: explicitly sort PRs by updated desc
  src/github.ts
  test/github.ts
Labels: size: m

#1691 fix: add initial-version to allowed properties in manifest schema
  schemas/config.json
  test/fixtures/manifest/config/initial-version.json
Labels: size: s

#1694 chore: configure blunderbuss
  .github/blunderbuss.yml
Labels: size: xs

#1646 feat: added expo strategy and updater
  README.md
  __snapshots__/app-json.js
  __snapshots__/cli.js
  docs/customizing.md
  src/factory.ts
  src/strategies/expo.ts
  src/strategies/node.ts
  src/updaters/expo/app-json.ts
  test/fixtures/strategies/expo/package.json
  test/strategies/expo.ts
  test/updaters/expo/app-json.ts
  test/updaters/fixtures/expo/app.json
Labels: size: l

#1689 feat: handle extremely large pull request body fields
  __snapshots__/pull-request-overflow-handler.js
  src/github.ts
  src/manifest.ts
  src/util/pull-request-body.ts
  src/util/pull-request-overflow-handler.ts
  test/fixtures/release-notes/overflow.txt
  test/github.ts
  test/manifest.ts
  test/util/pull-request-overflow-handler.ts
Labels: size: l

#1702 fix: updating a pull request uses overflow handler if body is too large
  src/github.ts
  src/manifest.ts
  test/github.ts
  test/helpers.ts
  test/manifest.ts
Labels: size: l

#1708 fix(python): version updater updates patch versions >= 10
  __snapshots__/python-file-with-version.js
  src/updaters/python/python-file-with-version.ts
  test/updaters/fixtures/version-with-long-patch.py
  test/updaters/python-file-with-version.ts
Labels: size: s

#1719 feat: extract and return the created release id
  src/github.ts
  src/manifest.ts
  test/cli.ts
  test/github.ts
  test/manifest.ts
  test/plugins/compatibility/linked-versions-workspace.ts
  test/plugins/linked-versions.ts
Labels: size: m

#1727 fix(maven-workspace): SNAPSHOT versions should not be included in the manifest
  src/plugins/maven-workspace.ts
  src/plugins/workspace.ts
  test/plugins/maven-workspace.ts
Labels: size: m
