Repository googleapis/release-please, pull requests merged in 2022-05, with the labels that each got.

#1414 fix(cargo-workspace): stop defaulting to updating all components
  __snapshots__/cargo-workspace.js
  src/plugins/cargo-workspace.ts
  src/plugins/workspace.ts
  test/plugins/cargo-workspace.ts
Labels: size: m

#1413 fix: node-workspace should not bump versions for peer dependencies
  __snapshots__/node-workspace.js
  src/plugins/node-workspace.ts
  test/fixtures/plugins/node-workspace/plugin1/package.json
  test/plugins/node-workspace.ts
Labels: automerge, size: m

#1412 feat: allow configuring separate-pull-requests per component
  src/manifest.ts
  src/plugins/merge.ts
  src/strategies/base.ts
  test/manifest.ts
Labels: size: l

#1421 chore: fix template exclude for sync-repo-settings
  owlbot.py
Labels: size: xs

#1425 fix: release tagging can find branch components
  src/strategies/base.ts
  test/manifest.ts
Labels: size: m

#1422 fix: throw ConfigurationError when required manifest config file is missing
  src/manifest.ts
  test/manifest.ts
Labels: size: m

#1429 fix: workspace plugins should update manifest versions
  src/factories/plugin-factory.ts
  src/manifest.ts
  src/plugins/cargo-workspace.ts
  src/plugins/node-workspace.ts
  src/plugins/workspace.ts
  test/factories/plugin-factory.ts
  test/plugins/node-workspace.ts
Labels: size: m

#1433 fix: add release labels if release PR was completed
  src/manifest.ts
  test/manifest.ts
Labels: automerge, size: m

#1432 fix: CommitSplit with includeEmpty should add commit to all packages
  src/util/commit-split.ts
  test/util/commit-split.ts
Labels: automerge, size: m

#1436 fix: Manifest.fromConfig should find branch component
  src/manifest.ts
  src/strategies/base.ts
  src/strategy.ts
  test/manifest.ts
Labels: size: s

#1442 fix: all release tag matching if includeComponentInTag is false
  src/manifest.ts
  test/manifest.ts
Labels: automerge, size: m

#1435 build(deps): update gts and ts, delete Node 8 and Node 10 configs
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/system-test.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  package.json
  src/github.ts
  src/strategies/base.ts
  test/github.ts
  test/strategies/base.ts
Labels: size: m

#1445 fix: allow brackets in custom pull request title
  src/util/pull-request-title.ts
  test/manifest.ts
  test/util/branch-name.ts
  test/util/pull-request-title.ts
Labels: automerge, size: m

#1446 feat: add maven-workspace plugin
  __snapshots__/maven-workspace.js
  __snapshots__/pom-xml.js
  docs/manifest-releaser.md
  src/factories/plugin-factory.ts
  src/plugins/cargo-workspace.ts
  src/plugins/maven-workspace.ts
  src/plugins/node-workspace.ts
  src/plugins/workspace.ts
  src/updaters/java/pom-xml.ts
  test/fixtures/plugins/maven-workspace/maven1/pom.xml
  test/fixtures/plugins/maven-workspace/maven2/pom.xml
  test/fixtures/plugins/maven-workspace/maven3/pom.xml
  test/fixtures/plugins/maven-workspace/maven4/pom.xml
  test/plugins/maven-workspace.ts
  test/updaters/fixtures/pom-with-dependencies.xml
  test/updaters/pom-xml.ts
Labels: automerge, size: xl

#1454 fix(deps): headings are now always H2
  __snapshots__/base.js
  __snapshots__/default-changelog-notes.js
  __snapshots__/linked-versions.js
  __snapshots__/manifest.js
  __snapshots__/rust.js
  package.json
Labels: size: m
