Repository googleapis/release-please, pull requests merged in 2022-06, with the labels that each got.

#1452 feat(yaml): add support for yaml updater
  __snapshots__/generic-yaml.js
  src/manifest.ts
  src/strategies/base.ts
  src/updaters/generic-yaml.ts
  test/strategies/base.ts
  test/updaters/fixtures/yaml/invalid.txt
  test/updaters/fixtures/yaml/multi.yaml
  test/updaters/generic-yaml.ts
Labels: size: l

#1451 fix: Fix parsing of tags with major versions higher than 9
  src/util/tag-name.ts
  test/util/tag-name.ts
Labels: size: s

#1461 docs: Correct broken link
  docs/customizing.md
Labels: size: xs

#1464 fix: set default bootstrap path to .
  src/bin/release-please.ts
  test/cli.ts
Labels: automerge, size: s

#1467 fix: factory errors for unknown types throw ConfigurationError instead of Error
  src/factories/changelog-notes-factory.ts
  src/factories/plugin-factory.ts
  src/factories/versioning-strategy-factory.ts
  src/factory.ts
  test/factories/versioning-strategy-factory.ts
Labels: size: s

#1469 fix: handle malformed manifest JSON and throw ConfigurationError
  src/manifest.ts
  test/manifest.ts
Labels: size: m

#1483 fix(go): hide unwanted changelog sections
  src/strategies/go-yoshi.ts
Labels: size: s

#1481 fix: pass GitHub API URLs from options to builder
  src/bin/release-please.ts
  test/cli.ts
Labels: size: m

#1479 fix(ruby-yoshi): don't remove PR link from changelog
  __snapshots__/ruby-yoshi.js
  src/strategies/ruby-yoshi.ts
Labels: size: xs

#1486 fix(dotnet-yoshi): handle existing google-cloud-dotnet history format
  __snapshots__/changelog.js
  src/strategies/dotnet-yoshi.ts
  src/updaters/changelog.ts
  test/updaters/changelog.ts
  test/updaters/fixtures/CHANGELOG-dotnet.md
Labels: automerge, size: m

#1489 deps: temporarily pin `@octokit/types` to 6.37.0
  .github/workflows/ci.yaml
  package.json
Labels: size: xs

#1488 docs: add missing option --include-v-in-tags to cli docs
  docs/cli.md
Labels: size: xs

#1494 Revert "deps: temporarily pin `@octokit/types` to 6.37.0"
  .github/workflows/ci.yaml
  package.json
Labels: size: xs

#1499 fix: pull request title component can include '/'
  src/util/pull-request-title.ts
  test/util/pull-request-title.ts
Labels: size: s

#1498 fix: correctly parse the changelog-type from the manifest config
  src/manifest.ts
  test/fixtures/manifest/config/changelog-type.json
  test/manifest.ts
Labels: size: s

#1496 feat: add manifest schemas
  package.json
  src/index.ts
  src/schemas/config.json
  src/schemas/manifest.json
  test/schemas.ts
Labels: size: l
