Repository googleapis/release-please, pull requests merged in 2022-08, with the labels that each got.

#1544 fix: handles pull request iterator when graphQL returns no files
  __snapshots__/github.js
  src/github.ts
  test/fixtures/merged-pull-requests-no-files.json
  test/github.ts
Labels: size: xl

#1535 fix: convert ReleaserConfig JSON keys when bootstrapping
  __snapshots__/bootstrapper.js
  src/manifest.ts
  src/updaters/release-please-config.ts
  test/bootstrapper.ts
Labels: automerge, size: m

#1551 docs: add design page/contributor guide
  README.md
  docs/design.md
Labels: size: l

#1556 fix(docs): Add missing `--repo-url` argument
  docs/manifest-releaser.md
Labels: size: xs

#1553 fix: php root-composer-update-packages version replace
  __snapshots__/php-composer-update-packages.js
  src/updaters/php/root-composer-update-packages.ts
  test/updaters/php-composer-update-packages.ts
Labels: size: m

#1550 feat: allow plugins to skip merging in-scope pull requests
  __snapshots__/cargo-workspace.js
  __snapshots__/linked-versions-workspace.js
  __snapshots__/linked-versions.js
  docs/manifest-releaser.md
  schemas/config.json
  src/factories/plugin-factory.ts
  src/manifest.ts
  src/plugins/cargo-workspace.ts
  src/plugins/linked-versions.ts
  src/plugins/workspace.ts
  test/plugins/cargo-workspace.ts
  test/plugins/compatibility/linked-versions-workspace.ts
  test/plugins/linked-versions.ts
Labels: size: l

#1555 feat: allow skipping snapshots for java strategies
  schemas/config.json
  src/manifest.ts
  src/strategies/base.ts
  src/strategies/java.ts
  test/factory.ts
  test/strategies/java.ts
Labels: size: m

#1564 chore: remove extraneous snapshot entries
  __snapshots__/php-composer-update-packages.js
Labels: size: s

#1563 build!: drop node 12 support
  .github/workflows/ci.yaml
  package.json
Labels: size: s

#1570 docs: clarifying releasable units and force-run label
  README.md
Labels: automerge, size: xs

#1572 feat: parse versioning type from the manifest config
  docs/manifest-releaser.md
  schemas/config.json
  src/manifest.ts
  test/fixtures/manifest/config/versioning.json
  test/manifest.ts
Labels: automerge, size: m

#1571 fix: throw underlying API error when the manifest fetch commits when determining the latest released version
  src/github.ts
  src/manifest.ts
  test/manifest.ts
Labels: size: m

#1577 build!: drop node 12 support (#1563)
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  package.json
Labels: size: s

#1585 feat: use file-cache from git-file-utils
  package.json
  src/github.ts
  src/strategies/dart.ts
  src/strategies/helm.ts
  src/strategies/java-yoshi.ts
  src/strategies/krm-blueprint.ts
  src/strategies/node.ts
  src/strategies/ocaml.ts
  src/strategies/php-yoshi.ts
  src/strategies/rust.ts
  src/update.ts
  src/util/file-cache.ts
  test/helpers.ts
  test/util/file-cache.ts
Labels: automerge, size: l

#1579 feat: customize pr body header
  __snapshots__/cli.js
  docs/cli.md
  docs/customizing.md
  package.json
  schemas/config.json
  src/bin/release-please.ts
  src/manifest.ts
  src/plugins/merge.ts
  src/strategies/base.ts
  src/strategies/dotnet-yoshi.ts
  src/strategies/java.ts
  src/strategies/php-yoshi.ts
  src/updaters/release-please-config.ts
  test/manifest.ts
Labels: size: m

#1584 feat: Allow $schema key in manifest config schema
  package.json
  schemas/config.json
  test/schemas.ts
Labels: size: xs

#1589 fix: Allow $schema key in manifest config schema
  schemas/config.json
Labels: size: xs

#1590 fix: convert `MissingFileError` thrown by `git-file-utils`
  src/github.ts
  test/github.ts
Labels: size: s

#1588 fix: use git-file-utils' cache for file search
  package.json
  src/github.ts
Labels: automerge, size: m

#1600 fix(deps): update code-suggester to 4.1.0
  package.json
Labels: size: xs

#1599 feat: maintain an instance logger
  src/commit.ts
  src/github.ts
  src/manifest.ts
  src/plugin.ts
  src/plugins/cargo-workspace.ts
  src/plugins/linked-versions.ts
  src/plugins/maven-workspace.ts
  src/plugins/merge.ts
  src/plugins/node-workspace.ts
  src/plugins/workspace.ts
  src/strategies/base.ts
  src/strategies/dotnet-yoshi.ts
  src/strategies/go-yoshi.ts
  src/strategies/java-yoshi.ts
  src/strategies/java.ts
  src/strategies/php-yoshi.ts
  src/strategies/python.ts
  src/strategies/rust.ts
  src/update.ts
  src/updaters/dart/pubspec-yaml.ts
  src/updaters/dotnet/apis.ts
  src/updaters/elixir/elixir-mix-exs.ts
  src/updaters/generic-json.ts
  src/updaters/generic-yaml.ts
  src/updaters/generic.ts
  src/updaters/helm/chart-yaml.ts
  src/updaters/java/java-update.ts
  src/updaters/java/versions-manifest.ts
  src/updaters/krm/krm-blueprint-version.ts
  src/updaters/node/package-json.ts
  src/updaters/node/package-lock-json.ts
  src/updaters/node/samples-package-json.ts
  src/updaters/ocaml/dune-project.ts
  src/updaters/ocaml/esy-json.ts
  src/updaters/ocaml/opam.ts
  src/updaters/php/php-manifest.ts
  src/updaters/php/root-composer-update-packages.ts
  src/updaters/python/pyproject-toml.ts
  src/updaters/rust/cargo-lock.ts
  src/updaters/rust/cargo-toml.ts
  src/updaters/terraform/module-version.ts
  src/util/branch-name.ts
  src/util/pull-request-body.ts
  src/util/pull-request-title.ts
  src/versioning-strategies/default.ts
Labels: size: l

#1603 fix: allow providing logger to GitHub.create
  src/github.ts
Labels: size: xs

#1606 fix: dont filter out root package in node workspace candidate filtering
  __snapshots__/node-workspace.js
  src/plugins/node-workspace.ts
  test/fixtures/plugins/node-workspace/package.json
  test/plugins/node-workspace.ts
Labels: size: s

#1615 fix: prepend release notes to non-conforming changelog
  __snapshots__/changelog.js
  src/updaters/changelog.ts
  test/updaters/changelog.ts
  test/updaters/fixtures/CHANGELOG-non-conforming.md
Labels: size: m

#1607 feat(plugins): introduce processCommits hook for plugins
  docs/manifest-releaser.md
  schemas/config.json
  src/factories/plugin-factory.ts
  src/manifest.ts
  src/plugin.ts
  src/plugins/sentence-case.ts
  test/manifest.ts
  test/plugins/sentence-case.ts
Labels: size: l
