Repository googleapis/release-please, pull requests merged in 2022-11, with the labels that each got.

#1730 fix(cargo-workspace): Update target dependencies in Cargo workspace packages
  __snapshots__/cargo-workspace.js
  src/plugins/cargo-workspace.ts
  test/fixtures/plugins/cargo-workspace/Cargo.toml
  test/fixtures/plugins/cargo-workspace/packages/rustE/Cargo.toml
  test/plugins/cargo-workspace.ts
Labels: size: m

#1733 fix: allow overlapping paths when splitting commits
  src/util/commit-split.ts
  test/util/commit-split.ts
Labels: size: s

#1736 fix(deps): bump minimum required xmldom to 0.8.4
  package.json
Labels: size: xs

#1723 feat(node-workspace): maintain current version range prefix
  __snapshots__/node-workspace.js
  src/plugins/node-workspace.ts
  test/plugins/node-workspace.ts
Labels: size: m

#1743 chore: Adding local testing steps to contributing guide
  CONTRIBUTING.md
Labels: size: s

#1744 chore: Adding new versioning strategies
  __snapshots__/cli.js
  docs/customizing.md
  src/factories/versioning-strategy-factory.ts
  src/versioning-strategies/always-bump-major.ts
  src/versioning-strategies/always-bump-minor.ts
  test/versioning-strategies/always-bump-major.ts
  test/versioning-strategies/always-bump-minor.ts
Labels: size: l

#1747 chore: Fixing typo in tests
  test/versioning-strategies/always-bump-major.ts
  test/versioning-strategies/always-bump-minor.ts
Labels: size: xs

#1748 fix(node-workspace): maintain the dependency version prefix in newCandidate
  __snapshots__/node-workspace.js
  src/plugins/node-workspace.ts
Labels: size: s

#1752 docs: add troubleshooting page
  README.md
  docs/troubleshooting.md
Labels: size: m

#1757 fix: handle issue links in BREAKING_CHANGE notes section
  __snapshots__/default-changelog-notes.js
  src/changelog-notes/default.ts
  test/changelog-notes/default-changelog-notes.ts
Labels: size: m

#1759 docs: add missing comma
  docs/manifest-releaser.md
Labels: size: xs

#1762 fix: handle incrementing ruby patch versions larger than 1 digit
  __snapshots__/version-rb.js
  src/updaters/ruby/version-rb.ts
  test/updaters/fixtures/version-with-long-patch.rb
  test/updaters/version-rb.ts
Labels: size: m
