Repository googleapis/release-please, pull requests merged in 2022-12, with the labels that each got.

#1760 fix: pass group-pull-request-title-pattern to strategies to parse releases
  __snapshots__/linked-versions-group-title.js
  src/manifest.ts
  src/plugins/linked-versions.ts
  src/strategies/base.ts
  src/strategy.ts
  test/helpers.ts
  test/plugins/compatibility/linked-versions-group-title.ts
Labels: size: m

#1770 fix: android version now correctly builds as a number
  __snapshots__/app-json.js
  src/updaters/expo/app-json.ts
Labels: size: xs

#1772 refactor!: parse conventional commits in manifest
  __snapshots__/base.js
  src/manifest.ts
  src/plugin.ts
  src/plugins/linked-versions.ts
  src/plugins/sentence-case.ts
  src/strategies/base.ts
  src/strategies/java.ts
  test/helpers.ts
  test/manifest.ts
  test/plugins/sentence-case.ts
  test/strategies/base.ts
  test/strategies/dart.ts
  test/strategies/dotnet-yoshi.ts
  test/strategies/elixir.ts
  test/strategies/expo.ts
  test/strategies/go-yoshi.ts
  test/strategies/go.ts
  test/strategies/helm.ts
  test/strategies/java-yoshi.ts
  test/strategies/java.ts
  test/strategies/krm-blueprint.ts
  test/strategies/maven.ts
  test/strategies/node.ts
  test/strategies/ocaml.ts
  test/strategies/php-yoshi.ts
  test/strategies/php.ts
  test/strategies/python.ts
  test/strategies/ruby-yoshi.ts
  test/strategies/ruby.ts
  test/strategies/rust.ts
  test/strategies/simple.ts
  test/strategies/terraform-module.ts
Labels: size: l

#1775 feat!: strategies can parse multiple releases from single release PR
  src/manifest.ts
  src/strategies/base.ts
  src/strategy.ts
Labels: size: s
