Repository googleapis/release-please, pull requests merged in 2023-05, with the labels that each got.

#1949 chore: remove manifest.json, Version.php, and ServiceBuilder.php
  src/strategies/php-yoshi.ts
  src/updaters/php/php-manifest.ts
  test/strategies/php-yoshi.ts
  test/updaters/fixtures/php/manifest.json
  test/updaters/php-manifest.ts
Labels: size: m

#1961 fix: allow configuring multiple, separate linked-versions plugins
  __snapshots__/linked-versions.js
  src/manifest.ts
  src/plugins/linked-versions.ts
  src/plugins/merge.ts
  src/util/branch-name.ts
  test/plugins/linked-versions.ts
Labels: size: m

#1940 feat: support package-lock.json version 3
  __snapshots__/package-lock-json.js
  src/updaters/node/package-lock-json.ts
  test/updaters/fixtures/package-lock-v3.json
  test/updaters/package-lock-json.ts
Labels: size: s

#1942 docs: Correct the linked-versions example
  docs/manifest-releaser.md
Labels: size: xs
