Repository googleapis/release-please, pull requests merged in 2023-11, with the labels that each got.

#2119 ci: add workflow job for building the action against head
  .github/workflows/ci.yaml
Labels: size: s

#2115 feat: customize PR body footer
  __snapshots__/cli.js
  docs/cli.md
  docs/customizing.md
  schemas/config.json
  src/bin/release-please.ts
  src/manifest.ts
  src/plugins/merge.ts
  src/strategies/base.ts
  src/strategies/dotnet-yoshi.ts
  src/updaters/release-please-config.ts
  test/manifest.ts
Labels: size: m

#2120 chore(deps): bump semver dependencies in lockfile
  package-lock.json
Labels: size: s

#2122 fix: set PR labels serially
  src/manifest.ts
Labels: size: s

#2124 docs: fix readme typo
  README.md
Labels: size: xs

#2123 fix: correctly parse standalone prerelease PR body
  src/util/pull-request-body.ts
  test/fixtures/release-notes/single-prerelease.txt
  test/util/pull-request-body.ts
Labels: size: s

#2117 feat(deps): refactor node-workspace plugin to drop lerna-lite/core
  __snapshots__/node-workspace.js
  __snapshots__/package-json.js
  package-lock.json
  package.json
  src/plugins/node-workspace.ts
  src/plugins/workspace.ts
  src/updaters/node/package-json.ts
  test/helpers.ts
  test/plugins/node-workspace.ts
  test/updaters/fixtures/package-with-dependencies.json
  test/updaters/package-json.ts
Labels: size: l

#2129 build: release on node 18
  .kokoro/release/publish.cfg
  owlbot.py
Labels: size: xs

#2131 docs: fix versioning strategy table rendering
  docs/customizing.md
Labels: size: xs

#2141 fix: backfill files by commit for rebased PRs
  __snapshots__/github.js
  src/github.ts
  test/fixtures/commits-since-rebase.json
  test/github.ts
Labels: size: m
