Repository googleapis/release-please, pull requests merged in 2023-07, with the labels that each got.

#2008 build: temporarily check in package-lock.json to resolve octokit dep issues
  package-lock.json
Labels: size: xl

#2001 docs: update README.md to note that cargo workspaces need a manifest driven release
  README.md
Labels: size: xs

#1981 feat: add PrereleaseVersioningStrategy
  __snapshots__/cli.js
  src/factories/versioning-strategy-factory.ts
  src/versioning-strategies/prerelease.ts
  test/versioning-strategies/prerelease.ts
Labels: size: l

#2013 docs(manifest-releaser): fix typos
  docs/manifest-releaser.md
Labels: size: xs
