Repository googleapis/release-please, pull requests merged in 2023-12, with the labels that each got.

#2153 feat: update VERSION file in PHP repo if it exists
  src/strategies/php.ts
  test/strategies/php.ts
Labels: size: s

#2147 feat(types): export types exposed by Manifest for use downstream
  src/index.ts
  src/manifest.ts
Labels: size: xs

#2094 fix(node-workspace): Add update-peer-dependencies option that also updates peer dependencies. Fixes #1943
  __snapshots__/node-workspace.js
  docs/manifest-releaser.md
  schemas/config.json
  src/factories/plugin-factory.ts
  src/manifest.ts
  src/plugins/node-workspace.ts
  test/plugins/node-workspace.ts
Labels: size: m

#2143 fix: pass pull request header and footer options to merge plugin
  __snapshots__/manifest.js
  src/manifest.ts
  src/plugins/merge.ts
  test/manifest.ts
Labels: size: m

#2158 build: switch to manifest
  .github/release-please.yml
  .release-please-manifest.json
  release-please-config.json
Labels: size: s

#2164 refactor: move updatePeerDependencies config to node-workspace plugin
  docs/manifest-releaser.md
  schemas/config.json
  src/manifest.ts
  src/plugins/node-workspace.ts
  test/factories/plugin-factory.ts
  test/fixtures/manifest/config/node-workspace-plugins.json
  test/manifest.ts
Labels: size: m

#2159 feat: export current release-please version as VERSION constant
  release-please-config.json
  src/index.ts
Labels: size: s

#2171 fix: old version range detection
  __snapshots__/package-json.js
  src/updaters/node/package-json.ts
Labels: size: xs

#2112 fix: Use strategies for workspace plugins.
  __snapshots__/node-workspace.js
  src/plugins/cargo-workspace.ts
  src/plugins/maven-workspace.ts
  src/plugins/node-workspace.ts
  src/plugins/workspace.ts
  src/strategies/base.ts
  src/strategies/java.ts
  src/strategies/php-yoshi.ts
  src/strategy.ts
  test/plugins/node-workspace.ts
Labels: size: l
