Repository googleapis/release-please, pull requests merged in 2023-03, with the labels that each got.

#1865 fix(sequential-calls): Use push instead of concat when returning releases
  src/manifest.ts
Labels: size: xs

#1855 fix(docs): :memo: Adding missing docs for include-component-in-tag
  docs/manifest-releaser.md
Labels: size: s

#1867 docs: add notes about `changelog-type` configuration
  docs/customizing.md
Labels: size: xs

#1852 fix(cargo-workspaces): expand globs in crate paths
  __snapshots__/cargo-workspace.js
  src/plugins/cargo-workspace.ts
  test/plugins/cargo-workspace.ts
  test/plugins/compatibility/linked-versions-workspace.ts
Labels: size: m

#1829 refactor: rename Salesforce to sfdx
  README.md
  __snapshots__/cli.js
  __snapshots__/sfdx-project-json.js
  docs/customizing.md
  src/factory.ts
  src/strategies/sfdx.ts
  src/updaters/sfdx/sfdx-project-json.ts
  test/fixtures/strategies/sfdx/sfdx-project.json
  test/strategies/sfdx.ts
  test/updaters/fixtures/sfdx-project.json
  test/updaters/sfdx-project-json.ts
Labels: size: m

#1877 fix(cargo-workspace): validate Cargo.toml version field
  .eslintrc.json
  src/plugins/cargo-workspace.ts
  test/plugins/cargo-workspace.ts
Labels: size: m

#1889 fix(cargo-workspace): find workspace modules on the target branch
  src/plugins/cargo-workspace.ts
  test/plugins/cargo-workspace.ts
  test/plugins/compatibility/linked-versions-workspace.ts
Labels: size: m
