Repository googleapis/release-please, pull requests merged in 2023-10, with the labels that each got.

#2086 docs: remove invalid expo example link
  README.md
Labels: size: xs

#2083 feat: prerelease type
  __snapshots__/cli.js
  docs/cli.md
  docs/customizing.md
  docs/manifest-releaser.md
  schemas/config.json
  src/bin/release-please.ts
  src/factories/versioning-strategy-factory.ts
  src/factory.ts
  src/manifest.ts
  src/version.ts
  src/versioning-strategies/default.ts
  src/versioning-strategies/dependency-manifest.ts
  src/versioning-strategies/prerelease.ts
  test/cli.ts
  test/factory.ts
  test/manifest.ts
  test/version.ts
  test/versioning-strategies/prerelease.ts
Labels: size: l

#2088 feat: update package-lock.json workspace entiry versions
  __snapshots__/package-lock-json.js
  src/updaters/node/package-lock-json.ts
  test/updaters/fixtures/package-lock-v3-workspace.json
  test/updaters/package-lock-json.ts
Labels: size: m

#2102 fix: releasable units should use version from pull-request body (fixes #2101)
  src/strategies/base.ts
  test/fixtures/release-notes/multiple-with-root.txt
  test/manifest.ts
Labels: size: m
