Repository googleapis/release-please, pull requests merged in 2023-04, with the labels that each got.

#1900 docs: show `extra-files` syntax for generic files
  docs/customizing.md
Labels: size: xs

#1906 fix(python): handle large version numbers in setup.cfg
  __snapshots__/setup-cfg.js
  src/updaters/python/setup-cfg.ts
  test/updaters/fixtures/setup-big-version.cfg
  test/updaters/setup-cfg.ts
Labels: size: m

#1875 feat: allow excluding file paths to filter out commits
  docs/manifest-releaser.md
  schemas/config.json
  src/manifest.ts
  src/util/commit-exclude.ts
  src/util/commit-split.ts
  src/util/commit-utils.ts
  test/fixtures/manifest/config/exclude-paths.json
  test/manifest.ts
  test/util/commit-exclude.ts
Labels: size: l

#1911 fix(xml): preserve trailing newline if the xml file had one
  __snapshots__/pom-xml.js
  src/updaters/base-xml.ts
  test/updaters/fixtures/pom-trailing-newline.xml
  test/updaters/pom-xml.ts
Labels: size: m

#1916 docs: add section about using squash-merge
  README.md
Labels: size: s

#1917 docs: clarify that the commit override does not work on plain merges
  README.md
Labels: size: xs

#1915 fix: needsBootstrap computation considers also tags
  src/manifest.ts
Labels: size: xs

#1926 docs: Add permissions stanza to manifest-releaser github script
  docs/manifest-releaser.md
Labels: size: xs
