Repository googleapis/release-please, pull requests merged in 2023-09, with the labels that each got.

#1930 docs: check `autorelease: pending` or `autorelease: triggered` in an old PR
  README.md
Labels: size: s

#2063 test: also test on node 18
  .github/workflows/ci.yaml
Labels: size: s

#2065 ci: only require node 18 tests
  .github/sync-repo-settings.yaml
Labels: size: xs

#2069 feat!: require node 18+
  .github/workflows/ci.yaml
  package.json
Labels: size: s

#2068 fix(deps): bump semver dependency version
  package-lock.json
  package.json
Labels: size: s

#2058 feat: Support pnpm workspaces
  package-lock.json
  package.json
  src/plugins/node-workspace.ts
  typings/config-chain.d.ts
Labels: size: xl

#2071 fix(deps): upgrade http-proxy-agent to v7
  package-lock.json
  package.json
  src/github.ts
Labels: size: m

#1935 feat: fallback to root package version if package ignores github release
  src/manifest.ts
Labels: size: s

#2072 feat: Use default updaters based on file extension
  docs/customizing.md
  src/strategies/base.ts
  test/strategies/base.ts
  test/strategies/java.ts
Labels: size: m
