Repository googleapis/release-please, pull requests merged in 2023-01, with the labels that each got.

#1790 feat(ruby): add Gemfile.Lock updater
  __snapshots__/gemfile-lock.js
  __snapshots__/version-rb.js
  src/strategies/ruby.ts
  src/updaters/ruby/common.ts
  src/updaters/ruby/gemfile-lock.ts
  src/updaters/ruby/version-rb.ts
  test/strategies/ruby.ts
  test/updaters/fixtures/Gemfile.lock
  test/updaters/fixtures/version-with-prerelease.rb
  test/updaters/gemfile-lock.ts
  test/updaters/ruby/common.ts
  test/updaters/version-rb.ts
Labels: size: l

#1794 fix(java-yoshi): throw MissingRequiredFile error if no versions.txt found
  src/strategies/java-yoshi.ts
  test/strategies/java-yoshi.ts
Labels: size: s

#1799 fix(deps): update code-suggester to 4.2.0
  package.json
Labels: size: xs

#1805 fix(ruby): gemfile.lock should not update when gem name is empty
  __snapshots__/gemfile-lock.js
  src/updaters/ruby/gemfile-lock.ts
  test/updaters/gemfile-lock.ts
Labels: size: m

#1808 feat: introduce ChangelogJson updater
  __snapshots__/changelog-json.js
  src/strategies/base.ts
  src/strategies/java.ts
  src/strategies/php-yoshi.ts
  src/updaters/changelog-json.ts
  test/updaters/changelog-json.ts
Labels: size: m

#1811 feat(cli): add ability to dynamically load release-please plugin
  __snapshots__/cli.js
  src/bin/release-please.ts
  src/index.ts
Labels: size: s

#1810 feat: introduce JavaYoshiMonoRepo strategy
  __snapshots__/cli.js
  __snapshots__/java-yoshi-mono-repo.js
  src/factory.ts
  src/plugins/maven-workspace.ts
  src/strategies/java-yoshi-mono-repo.ts
  test/fixtures/strategies/java-yoshi/artifact-map.json
  test/fixtures/strategies/java-yoshi/changelog.json
  test/strategies/java-yoshi-mono-repo.ts
Labels: size: l

#1815 feat: add Salesforce strategy
  README.md
  __snapshots__/cli.js
  __snapshots__/sfdx-project-json.js
  docs/customizing.md
  src/factory.ts
  src/strategies/salesforce.ts
  src/updaters/salesforce/sfdx-project-json.ts
  test/fixtures/strategies/salesforce/sfdx-project.json
  test/strategies/salesforce.ts
  test/updaters/fixtures/sfdx-project.json
  test/updaters/sfdx-project-json.ts
Labels: size: l

#1819 feat: add support for yarn workspace versions
  __snapshots__/node-workspace.js
  package.json
  src/plugins/node-workspace.ts
  test/fixtures/plugins/node-workspace/node5/package.json
  test/plugins/node-workspace.ts
Labels: size: m

#1823 feat(node): add support for changelog.json in Node
  __snapshots__/node.js
  src/strategies/node.ts
  test/fixtures/strategies/node/changelog.json
  test/strategies/node.ts
Labels: size: m

#1827 fix: filter changelog.json commits based on changelog sections
  src/strategies/java-yoshi-mono-repo.ts
  src/strategies/node.ts
  src/util/filter-commits.ts
  test/util/filter-commits.ts
Labels: size: m

#1830 feat(changelog.json): include referenced issues/prs
  __snapshots__/changelog-json.js
  __snapshots__/java-yoshi-mono-repo.js
  __snapshots__/node.js
  src/updaters/changelog-json.ts
Labels: size: s

#1833 feat: Add generic TOML updater
  __snapshots__/generic-toml.js
  docs/customizing.md
  src/manifest.ts
  src/strategies/base.ts
  src/updaters/generic-toml.ts
  src/util/toml-edit.ts
  test/strategies/base.ts
  test/updaters/fixtures/toml/invalid.txt
  test/updaters/generic-toml.ts
Labels: size: l

#1835 feat: add toml generic updater option to extra-files schema
  schemas/config.json
Labels: size: xs

#1837 fix: Support TOML up to v1.0.0-rc.1 spec.
  __snapshots__/generic-toml.js
  package.json
  test/updaters/fixtures/toml/v1.0.0.toml
  test/updaters/generic-toml.ts
Labels: size: m
