Repository googleapis/release-please, pull requests merged in 2024-01, with the labels that each got.

#2162 feat: add root package-lock.json support
  __snapshots__/package-lock-json.js
  package.json
  src/plugins/node-workspace.ts
  src/strategies/node.ts
  src/updaters/node/package-json.ts
  src/updaters/node/package-lock-json.ts
  test/updaters/fixtures/package-lock-v3-workspace.json
  test/updaters/package-lock-json.ts
Labels: size: m

#2183 build: disable owlbot from touching files in this repo
  owlbot.py
Labels: size: s

#2185 build: restore extra-files config
  release-please-config.json
Labels: size: xs

#2192 feat: set "version" if it's in composer.json for php-yoshi config
  src/strategies/php-yoshi.ts
Labels: size: xs

#2199 fix(php): do not add version to root version map
  src/strategies/php-yoshi.ts
  test/strategies/php-yoshi.ts
Labels: size: m

#2201 feat: set 'version' of composer.json in RootComposerUpdatePackages
  __snapshots__/php-composer-update-packages.js
  __snapshots__/root-composer-update-packages.js
  src/strategies/php-yoshi.ts
  src/strategies/php.ts
  src/updaters/php/root-composer-update-packages.ts
  test/updaters/php-composer-update-packages.ts
  test/updaters/root-composer-update-packages.ts
Labels: size: m
