Repository googleapis/release-please, pull requests merged in 2024-03, with the labels that each got.

#2239 feat: add support for `bazel`
  README.md
  __snapshots__/cli.js
  __snapshots__/module-bazel.js
  src/factory.ts
  src/strategies/bazel.ts
  src/updaters/bazel/module-bazel.ts
  test/strategies/bazel.ts
  test/updaters/fixtures/MODULE-inline.bazel
  test/updaters/fixtures/MODULE-missing.bazel
  test/updaters/fixtures/MODULE-order.bazel
  test/updaters/fixtures/MODULE.bazel
  test/updaters/module-bazel.ts
Labels: size: l

#2228 feat: update VERSION file in php-yoshi repo if it exists
  src/strategies/php-yoshi.ts
  test/strategies/php-yoshi.ts
Labels: size: s

#2227 fix: Support generic updater
  docs/customizing.md
  src/manifest.ts
  src/strategies/base.ts
  test/strategies/base.ts
Labels: size: s

#2241 fix: draft-pull-requests config
  src/manifest.ts
  test/fixtures/manifest/config/draft-pull-request.json
  test/manifest.ts
Labels: size: s

#2247 fix: respect signoff in config
  src/manifest.ts
Labels: size: xs
