Repository googleapis/release-please, pull requests merged in 2024-09, with the labels that each got.

#2348 fix: fix comment at release pr is ugly
  src/manifest.ts
Labels: size: xs

#2344 chore: add missing generic updaters in to release please config schema extraFiles
  schemas/config.json
Labels: size: s

#2367 fix: don't escape html tags inside of inline code in release notes
  __snapshots__/default-changelog-notes.js
  src/changelog-notes/default.ts
  test/changelog-notes/default-changelog-notes.ts
Labels: size: s

#2253 fix: use regex to replace version in GenericJSON updater
  __snapshots__/generic-json.js
  src/updaters/generic-json.ts
  test/updaters/fixtures/renovate-shared-preset.json
  test/updaters/generic-json.ts
Labels: size: m

#2283 fix: respect `tagSeparator` and `includeVInTag` everywhere
  src/manifest.ts
  src/strategies/php-yoshi.ts
Labels: size: s

#2331 docs: update manifest-releaser docs to add some clarification around …
  docs/manifest-releaser.md
Labels: size: s

#2243 docs: fix xml mention in json docs
  docs/customizing.md
Labels: size: xs

#2323 fix: prevent open release PRs from being mistaken as current releases
  CONTRIBUTING.md
  __snapshots__/github.js
  src/github.ts
  src/manifest.ts
  src/pull-request.ts
  test/manifest.ts
Labels: size: s

#2326 refactor: print error message of unparsed commits
  src/commit.ts
Labels: size: xs

#2375 ci: enable merge queue ci
  .github/workflows/ci.yaml
Labels: size: xs

#2255 docs: Add troubleshooting guide for the scenario that release PR is merged with `autorelease:closed`
  docs/troubleshooting.md
Labels: size: xs

#2249 fix: support-node-workspace-plugin-prerelease
  __snapshots__/node-workspace.js
  src/plugins/node-workspace.ts
  test/plugins/node-workspace.ts
Labels: size: m

#2320 fix: use strategies for cargo workspace plugin (rust)
  src/plugins/cargo-workspace.ts
Labels: size: s

#2251 docs: add expo project example
  README.md
Labels: size: xs

#2330 feat: Introduce `componentNoSpace` parameter (Removes whitespace character from `${component}` title pattern)
  __snapshots__/cli.js
  __snapshots__/manifest.js
  docs/cli.md
  docs/customizing.md
  schemas/config.json
  src/bin/release-please.ts
  src/manifest.ts
  src/plugins/merge.ts
  src/strategies/base.ts
  src/strategies/java.ts
  src/updaters/release-please-config.ts
  src/util/pull-request-title.ts
  test/manifest.ts
  test/util/pull-request-title.ts
Labels: size: l

#2358 feat: handle multiple commits in a single message
  src/commit.ts
  test/commits.ts
  test/fixtures/commit-messages/multiple-commits-single-message.txt
Labels: size: m
