Repository googleapis/release-please, pull requests merged in 2025-02, with the labels that each got.

#2486 fix(deps): bump dependency versions
  package-lock.json
Labels: size: m

#2488 docs(python): suggest pyproject.toml instead of setup.py
  README.md
Labels: size: xs

#2491 feat: Manifest.createRelease to return PR numbers
  src/manifest.ts
  test/cli.ts
  test/manifest.ts
Labels: size: s
